/**
 * AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
 * Generated by scripts/fetch-tickers.ts via Finnhub API.
 * Timestamp: 2026-08-05T17:58:24.654Z
 */

export type EquityTicker = {
  symbol: string
  name: string
  sector: string
  aliases: readonly string[]
}

export const US_EQUITIES_TICKERS: readonly EquityTicker[] = [
  {
    "symbol": "AAPL",
    "name": "APPLE INC",
    "sector": "tech",
    "aliases": [
      "Apple",
      "iPhone",
      "Mac",
      "iPad",
      "AAPL",
      "Tim Cook"
    ]
  },
  {
    "symbol": "MSFT",
    "name": "MICROSOFT CORP",
    "sector": "tech",
    "aliases": [
      "Microsoft",
      "Azure",
      "Windows",
      "Office",
      "MSFT",
      "Satya Nadella"
    ]
  },
  {
    "symbol": "NVDA",
    "name": "NVIDIA CORP",
    "sector": "tech",
    "aliases": [
      "Nvidia",
      "GeForce",
      "CUDA",
      "NVDA",
      "Jensen Huang"
    ]
  },
  {
    "symbol": "AMZN",
    "name": "AMAZON.COM INC",
    "sector": "tech",
    "aliases": [
      "Amazon",
      "AWS",
      "Prime",
      "AMZN",
      "Andy Jassy"
    ]
  },
  {
    "symbol": "GOOGL",
    "name": "ALPHABET INC-CL A",
    "sector": "tech",
    "aliases": [
      "Alphabet",
      "Google",
      "YouTube",
      "DeepMind",
      "GOOGL",
      "GOOG",
      "Sundar Pichai"
    ]
  },
  {
    "symbol": "META",
    "name": "META PLATFORMS INC-CLASS A",
    "sector": "tech",
    "aliases": [
      "Meta",
      "Facebook",
      "Instagram",
      "WhatsApp",
      "META",
      "Mark Zuckerberg"
    ]
  },
  {
    "symbol": "TSLA",
    "name": "TESLA INC",
    "sector": "consumer",
    "aliases": [
      "Tesla",
      "Elon Musk",
      "TSLA",
      "Cybertruck"
    ]
  },
  {
    "symbol": "BRK.B",
    "name": "BERKSHIRE HATHAWAY INC-CL B",
    "sector": "finance",
    "aliases": [
      "Berkshire Hathaway",
      "Berkshire",
      "Warren Buffett",
      "BRK.B",
      "BRK-B",
      "Buffett"
    ]
  },
  {
    "symbol": "LLY",
    "name": "ELI LILLY & CO",
    "sector": "healthcare",
    "aliases": [
      "Eli Lilly",
      "Lilly",
      "LLY",
      "Zepbound",
      "Mounjaro"
    ]
  },
  {
    "symbol": "AVGO",
    "name": "BROADCOM INC",
    "sector": "tech",
    "aliases": [
      "Broadcom",
      "AVGO",
      "Hock Tan"
    ]
  },
  {
    "symbol": "JPM",
    "name": "JPMORGAN CHASE & CO",
    "sector": "finance",
    "aliases": [
      "JPMorgan",
      "JPMorgan Chase",
      "JPM",
      "Jamie Dimon"
    ]
  },
  {
    "symbol": "WMT",
    "name": "WALMART INC",
    "sector": "consumer",
    "aliases": [
      "Walmart",
      "WMT",
      "Doug McMillon"
    ]
  },
  {
    "symbol": "UNH",
    "name": "UNITEDHEALTH GROUP INC",
    "sector": "healthcare",
    "aliases": [
      "UnitedHealth",
      "United Health",
      "UNH"
    ]
  },
  {
    "symbol": "V",
    "name": "VISA INC-CLASS A SHARES",
    "sector": "finance",
    "aliases": [
      "Visa",
      "V"
    ]
  },
  {
    "symbol": "XOM",
    "name": "EXXONMOBIL HOLDINGS CORP",
    "sector": "energy",
    "aliases": [
      "Exxon Mobil",
      "Exxon",
      "XOM",
      "Darren Woods"
    ]
  },
  {
    "symbol": "MA",
    "name": "MASTERCARD INC - A",
    "sector": "finance",
    "aliases": [
      "Mastercard",
      "MA"
    ]
  },
  {
    "symbol": "ORCL",
    "name": "ORACLE CORP",
    "sector": "tech",
    "aliases": [
      "Oracle",
      "ORCL",
      "Larry Ellison"
    ]
  },
  {
    "symbol": "COST",
    "name": "COSTCO WHOLESALE CORP",
    "sector": "consumer",
    "aliases": [
      "Costco",
      "COST"
    ]
  },
  {
    "symbol": "HD",
    "name": "HOME DEPOT INC",
    "sector": "consumer",
    "aliases": [
      "Home Depot",
      "HD"
    ]
  },
  {
    "symbol": "PG",
    "name": "PROCTER & GAMBLE CO/THE",
    "sector": "consumer",
    "aliases": [
      "Procter & Gamble",
      "P&G",
      "PG"
    ]
  },
  {
    "symbol": "JNJ",
    "name": "JOHNSON & JOHNSON",
    "sector": "healthcare",
    "aliases": [
      "Johnson & Johnson",
      "J&J",
      "JNJ"
    ]
  },
  {
    "symbol": "NFLX",
    "name": "NETFLIX INC",
    "sector": "tech",
    "aliases": [
      "Netflix",
      "NFLX"
    ]
  },
  {
    "symbol": "BAC",
    "name": "BANK OF AMERICA CORP",
    "sector": "finance",
    "aliases": [
      "Bank of America",
      "BofA",
      "BAC",
      "Brian Moynihan"
    ]
  },
  {
    "symbol": "ABBV",
    "name": "ABBVIE INC",
    "sector": "healthcare",
    "aliases": [
      "AbbVie",
      "ABBV",
      "Humira"
    ]
  },
  {
    "symbol": "CRM",
    "name": "SALESFORCE INC",
    "sector": "tech",
    "aliases": [
      "Salesforce",
      "CRM",
      "Marc Benioff"
    ]
  },
  {
    "symbol": "CVX",
    "name": "CHEVRON CORP",
    "sector": "energy",
    "aliases": [
      "Chevron",
      "CVX",
      "Mike Wirth"
    ]
  },
  {
    "symbol": "WFC",
    "name": "WELLS FARGO & CO",
    "sector": "finance",
    "aliases": [
      "Wells Fargo",
      "WFC",
      "Charlie Scharf"
    ]
  },
  {
    "symbol": "KO",
    "name": "COCA-COLA CO/THE",
    "sector": "consumer",
    "aliases": [
      "Coca-Cola",
      "Coke",
      "KO"
    ]
  },
  {
    "symbol": "TMUS",
    "name": "T-MOBILE US INC",
    "sector": "telecom",
    "aliases": [
      "T-Mobile",
      "TMUS"
    ]
  },
  {
    "symbol": "CSCO",
    "name": "CISCO SYSTEMS INC",
    "sector": "tech",
    "aliases": [
      "Cisco",
      "Cisco Systems",
      "CSCO"
    ]
  },
  {
    "symbol": "PEP",
    "name": "PEPSICO INC",
    "sector": "consumer",
    "aliases": [
      "PepsiCo",
      "Pepsi",
      "PEP"
    ]
  },
  {
    "symbol": "IBM",
    "name": "INTL BUSINESS MACHINES CORP",
    "sector": "tech",
    "aliases": [
      "IBM",
      "Arvind Krishna"
    ]
  },
  {
    "symbol": "MS",
    "name": "MORGAN STANLEY",
    "sector": "finance",
    "aliases": [
      "Morgan Stanley",
      "MS",
      "Ted Pick"
    ]
  },
  {
    "symbol": "ACN",
    "name": "ACCENTURE PLC-CL A",
    "sector": "tech",
    "aliases": [
      "Accenture",
      "ACN"
    ]
  },
  {
    "symbol": "LIN",
    "name": "LINDE PLC",
    "sector": "materials",
    "aliases": [
      "Linde",
      "LIN"
    ]
  },
  {
    "symbol": "MCD",
    "name": "MCDONALD'S CORP",
    "sector": "consumer",
    "aliases": [
      "McDonald's",
      "McDonalds",
      "MCD"
    ]
  },
  {
    "symbol": "DIS",
    "name": "WALT DISNEY CO/THE",
    "sector": "media",
    "aliases": [
      "Disney",
      "Walt Disney",
      "DIS",
      "Bob Iger"
    ]
  },
  {
    "symbol": "ABT",
    "name": "ABBOTT LABORATORIES",
    "sector": "healthcare",
    "aliases": [
      "Abbott",
      "Abbott Laboratories",
      "ABT"
    ]
  },
  {
    "symbol": "PM",
    "name": "PHILIP MORRIS INTERNATIONAL",
    "sector": "consumer",
    "aliases": [
      "Philip Morris",
      "PM"
    ]
  },
  {
    "symbol": "GE",
    "name": "GENERAL ELECTRIC",
    "sector": "industrials",
    "aliases": [
      "General Electric",
      "GE",
      "GE Aerospace"
    ]
  },
  {
    "symbol": "INTU",
    "name": "INTUIT INC",
    "sector": "tech",
    "aliases": [
      "Intuit",
      "TurboTax",
      "QuickBooks",
      "INTU"
    ]
  },
  {
    "symbol": "QCOM",
    "name": "QUALCOMM INC",
    "sector": "tech",
    "aliases": [
      "Qualcomm",
      "Snapdragon",
      "QCOM"
    ]
  },
  {
    "symbol": "DHR",
    "name": "DANAHER CORP",
    "sector": "healthcare",
    "aliases": [
      "Danaher",
      "DHR"
    ]
  },
  {
    "symbol": "CAT",
    "name": "CATERPILLAR INC",
    "sector": "industrials",
    "aliases": [
      "Caterpillar",
      "CAT"
    ]
  },
  {
    "symbol": "AMD",
    "name": "ADVANCED MICRO DEVICES",
    "sector": "tech",
    "aliases": [
      "AMD",
      "Advanced Micro Devices",
      "Radeon",
      "Ryzen",
      "Lisa Su"
    ]
  },
  {
    "symbol": "VRTX",
    "name": "VERTEX PHARMACEUTICALS INC",
    "sector": "healthcare",
    "aliases": [
      "Vertex",
      "Vertex Pharmaceuticals",
      "VRTX"
    ]
  },
  {
    "symbol": "TXN",
    "name": "TEXAS INSTRUMENTS INC",
    "sector": "tech",
    "aliases": [
      "Texas Instruments",
      "TXN"
    ]
  },
  {
    "symbol": "BKNG",
    "name": "BOOKING HOLDINGS INC",
    "sector": "consumer",
    "aliases": [
      "Booking Holdings",
      "Booking.com",
      "BKNG",
      "Priceline"
    ]
  },
  {
    "symbol": "AMAT",
    "name": "APPLIED MATERIALS INC",
    "sector": "tech",
    "aliases": [
      "Applied Materials",
      "AMAT"
    ]
  },
  {
    "symbol": "PFE",
    "name": "PFIZER INC",
    "sector": "healthcare",
    "aliases": [
      "Pfizer",
      "PFE",
      "Albert Bourla"
    ]
  },
  {
    "symbol": "T",
    "name": "AT&T INC",
    "sector": "telecom",
    "aliases": [
      "AT&T",
      "T"
    ]
  },
  {
    "symbol": "NOW",
    "name": "SERVICENOW INC",
    "sector": "tech",
    "aliases": [
      "ServiceNow",
      "NOW",
      "Bill McDermott"
    ]
  },
  {
    "symbol": "LOW",
    "name": "LOWE'S COS INC",
    "sector": "consumer",
    "aliases": [
      "Lowe's",
      "Lowes",
      "LOW"
    ]
  },
  {
    "symbol": "AMGN",
    "name": "AMGEN INC",
    "sector": "healthcare",
    "aliases": [
      "Amgen",
      "AMGN"
    ]
  },
  {
    "symbol": "C",
    "name": "CITIGROUP INC",
    "sector": "finance",
    "aliases": [
      "Citigroup",
      "Citi",
      "C",
      "Jane Fraser"
    ]
  },
  {
    "symbol": "SPGI",
    "name": "S&P GLOBAL INC",
    "sector": "finance",
    "aliases": [
      "S&P Global",
      "SPGI"
    ]
  },
  {
    "symbol": "ISRG",
    "name": "INTUITIVE SURGICAL INC",
    "sector": "healthcare",
    "aliases": [
      "Intuitive Surgical",
      "ISRG",
      "da Vinci"
    ]
  },
  {
    "symbol": "UNP",
    "name": "UNION PACIFIC CORP",
    "sector": "industrials",
    "aliases": [
      "Union Pacific",
      "UNP"
    ]
  },
  {
    "symbol": "GS",
    "name": "GOLDMAN SACHS GROUP INC",
    "sector": "finance",
    "aliases": [
      "Goldman Sachs",
      "Goldman",
      "GS",
      "David Solomon"
    ]
  },
  {
    "symbol": "COP",
    "name": "CONOCOPHILLIPS",
    "sector": "energy",
    "aliases": [
      "ConocoPhillips",
      "COP"
    ]
  },
  {
    "symbol": "HON",
    "name": "HONEYWELL INTERNATIONAL INC",
    "sector": "industrials",
    "aliases": [
      "Honeywell",
      "HON"
    ]
  },
  {
    "symbol": "CMCSA",
    "name": "COMCAST CORP-CLASS A",
    "sector": "media",
    "aliases": [
      "Comcast",
      "CMCSA",
      "Xfinity"
    ]
  },
  {
    "symbol": "RTX",
    "name": "RTX CORP",
    "sector": "industrials",
    "aliases": [
      "RTX",
      "Raytheon",
      "Pratt & Whitney"
    ]
  },
  {
    "symbol": "PGR",
    "name": "PROGRESSIVE CORP",
    "sector": "finance",
    "aliases": [
      "Progressive",
      "PGR"
    ]
  },
  {
    "symbol": "TJX",
    "name": "TJX COMPANIES INC",
    "sector": "consumer",
    "aliases": [
      "TJX",
      "TJ Maxx",
      "Marshalls"
    ]
  },
  {
    "symbol": "EOG",
    "name": "EOG RESOURCES INC",
    "sector": "energy",
    "aliases": [
      "EOG Resources",
      "EOG"
    ]
  },
  {
    "symbol": "SCHW",
    "name": "SCHWAB (CHARLES) CORP",
    "sector": "finance",
    "aliases": [
      "Charles Schwab",
      "Schwab",
      "SCHW"
    ]
  },
  {
    "symbol": "SYK",
    "name": "STRYKER CORP",
    "sector": "healthcare",
    "aliases": [
      "Stryker",
      "SYK"
    ]
  },
  {
    "symbol": "BA",
    "name": "BOEING CO/THE",
    "sector": "industrials",
    "aliases": [
      "Boeing",
      "BA",
      "737 MAX",
      "Kelly Ortberg"
    ]
  },
  {
    "symbol": "ELV",
    "name": "ELEVANCE HEALTH INC",
    "sector": "healthcare",
    "aliases": [
      "Elevance Health",
      "Anthem",
      "ELV"
    ]
  },
  {
    "symbol": "DE",
    "name": "DEERE & CO",
    "sector": "industrials",
    "aliases": [
      "Deere",
      "John Deere",
      "DE"
    ]
  },
  {
    "symbol": "ADP",
    "name": "AUTOMATIC DATA PROCESSING",
    "sector": "tech",
    "aliases": [
      "ADP"
    ]
  },
  {
    "symbol": "VZ",
    "name": "VERIZON COMMUNICATIONS INC",
    "sector": "telecom",
    "aliases": [
      "Verizon",
      "VZ"
    ]
  },
  {
    "symbol": "NKE",
    "name": "NIKE INC -CL B",
    "sector": "consumer",
    "aliases": [
      "Nike",
      "NKE",
      "Air Jordan"
    ]
  },
  {
    "symbol": "BSX",
    "name": "BOSTON SCIENTIFIC CORP",
    "sector": "healthcare",
    "aliases": [
      "Boston Scientific",
      "BSX"
    ]
  },
  {
    "symbol": "MMC",
    "name": "Marsh & McLennan Companies Inc.",
    "sector": "finance",
    "aliases": [
      "Marsh McLennan",
      "Marsh & McLennan",
      "MMC"
    ]
  },
  {
    "symbol": "LRCX",
    "name": "LAM RESEARCH CORP",
    "sector": "tech",
    "aliases": [
      "Lam Research",
      "LRCX"
    ]
  },
  {
    "symbol": "ADBE",
    "name": "ADOBE INC",
    "sector": "tech",
    "aliases": [
      "Adobe",
      "Photoshop",
      "ADBE",
      "Shantanu Narayen"
    ]
  },
  {
    "symbol": "BX",
    "name": "BLACKSTONE INC",
    "sector": "finance",
    "aliases": [
      "Blackstone",
      "BX",
      "Stephen Schwarzman"
    ]
  },
  {
    "symbol": "PLTR",
    "name": "PALANTIR TECHNOLOGIES INC-A",
    "sector": "tech",
    "aliases": [
      "Palantir",
      "PLTR",
      "Palantir Technologies",
      "Alex Karp"
    ]
  },
  {
    "symbol": "GILD",
    "name": "GILEAD SCIENCES INC",
    "sector": "healthcare",
    "aliases": [
      "Gilead",
      "Gilead Sciences",
      "GILD"
    ]
  },
  {
    "symbol": "LMT",
    "name": "LOCKHEED MARTIN CORP",
    "sector": "industrials",
    "aliases": [
      "Lockheed Martin",
      "Lockheed",
      "LMT"
    ]
  },
  {
    "symbol": "MDLZ",
    "name": "MONDELEZ INTERNATIONAL INC-A",
    "sector": "consumer",
    "aliases": [
      "Mondelez",
      "MDLZ",
      "Oreo"
    ]
  },
  {
    "symbol": "MU",
    "name": "MICRON TECHNOLOGY INC",
    "sector": "tech",
    "aliases": [
      "Micron",
      "Micron Technology",
      "MU"
    ]
  },
  {
    "symbol": "FI",
    "name": "Fiserv Inc.",
    "sector": "tech",
    "aliases": [
      "Fiserv",
      "FI",
      "FISV"
    ]
  },
  {
    "symbol": "SBUX",
    "name": "STARBUCKS CORP",
    "sector": "consumer",
    "aliases": [
      "Starbucks",
      "SBUX",
      "Brian Niccol"
    ]
  },
  {
    "symbol": "PANW",
    "name": "PALO ALTO NETWORKS INC",
    "sector": "tech",
    "aliases": [
      "Palo Alto Networks",
      "PANW",
      "Nikesh Arora"
    ]
  },
  {
    "symbol": "REGN",
    "name": "REGENERON PHARMACEUTICALS",
    "sector": "healthcare",
    "aliases": [
      "Regeneron",
      "REGN",
      "Dupixent"
    ]
  },
  {
    "symbol": "CB",
    "name": "CHUBB LTD",
    "sector": "finance",
    "aliases": [
      "Chubb",
      "CB"
    ]
  },
  {
    "symbol": "CI",
    "name": "THE CIGNA GROUP",
    "sector": "healthcare",
    "aliases": [
      "Cigna",
      "CI"
    ]
  },
  {
    "symbol": "UPS",
    "name": "UNITED PARCEL SERVICE-CL B",
    "sector": "industrials",
    "aliases": [
      "UPS",
      "United Parcel Service",
      "Carol Tomé"
    ]
  },
  {
    "symbol": "PH",
    "name": "PARKER HANNIFIN CORP",
    "sector": "industrials",
    "aliases": [
      "Parker Hannifin",
      "PH"
    ]
  },
  {
    "symbol": "KMI",
    "name": "KINDER MORGAN INC",
    "sector": "energy",
    "aliases": [
      "Kinder Morgan",
      "KMI"
    ]
  },
  {
    "symbol": "AMT",
    "name": "American Tower Corp.",
    "sector": "realestate",
    "aliases": [
      "American Tower",
      "AMT"
    ]
  },
  {
    "symbol": "SHW",
    "name": "SHERWIN-WILLIAMS CO/THE",
    "sector": "materials",
    "aliases": [
      "Sherwin-Williams",
      "SHW"
    ]
  },
  {
    "symbol": "MO",
    "name": "ALTRIA GROUP INC",
    "sector": "consumer",
    "aliases": [
      "Altria",
      "MO",
      "Marlboro"
    ]
  },
  {
    "symbol": "SLB",
    "name": "SLB LTD",
    "sector": "energy",
    "aliases": [
      "Schlumberger",
      "SLB"
    ]
  },
  {
    "symbol": "CVS",
    "name": "CVS HEALTH CORP",
    "sector": "healthcare",
    "aliases": [
      "CVS",
      "CVS Health"
    ]
  },
  {
    "symbol": "CDNS",
    "name": "CADENCE DESIGN SYS INC",
    "sector": "tech",
    "aliases": [
      "Cadence",
      "CDNS"
    ]
  },
  {
    "symbol": "KKR",
    "name": "KKR & CO INC",
    "sector": "finance",
    "aliases": [
      "KKR"
    ]
  }
] as const

export const US_EQUITIES_SYMBOLS: readonly string[] = US_EQUITIES_TICKERS.map((t) => t.symbol)

export const US_EQUITIES_ALIASES: Record<string, readonly string[]> = Object.fromEntries(
  US_EQUITIES_TICKERS.map((t) => [t.symbol, t.aliases])
)
