/**
 * AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
 * Generated by scripts/fetch-tickers.ts via Finnhub API + S&P 500 constituents.
 * Timestamp: 2026-08-05T18:06:52.769Z
 */

export type EquityTicker = {
  symbol: string
  name: string
  sector: string
  aliases: readonly string[]
}

export const US_EQUITIES_TICKERS: readonly EquityTicker[] = [
  {
    "symbol": "MMM",
    "name": "3M CO",
    "sector": "industrials",
    "aliases": [
      "MMM",
      "3M CO"
    ]
  },
  {
    "symbol": "AOS",
    "name": "SMITH (A.O.) CORP",
    "sector": "industrials",
    "aliases": [
      "AOS",
      "SMITH (A.O.) CORP"
    ]
  },
  {
    "symbol": "ABT",
    "name": "ABBOTT LABORATORIES",
    "sector": "healthcare",
    "aliases": [
      "ABT",
      "ABBOTT LABORATORIES"
    ]
  },
  {
    "symbol": "ABBV",
    "name": "ABBVIE INC",
    "sector": "healthcare",
    "aliases": [
      "ABBV",
      "ABBVIE INC"
    ]
  },
  {
    "symbol": "ACN",
    "name": "ACCENTURE PLC-CL A",
    "sector": "tech",
    "aliases": [
      "ACN",
      "ACCENTURE-CL A",
      "ACCENTURE PLC-CL A"
    ]
  },
  {
    "symbol": "ADBE",
    "name": "ADOBE INC",
    "sector": "tech",
    "aliases": [
      "ADBE",
      "ADOBE INC"
    ]
  },
  {
    "symbol": "AMD",
    "name": "ADVANCED MICRO DEVICES",
    "sector": "tech",
    "aliases": [
      "AMD",
      "ADVANCED MICRO DEVICES"
    ]
  },
  {
    "symbol": "AES",
    "name": "AES CORP",
    "sector": "utilities",
    "aliases": [
      "AES",
      "AES CORP"
    ]
  },
  {
    "symbol": "AFL",
    "name": "AFLAC INC",
    "sector": "finance",
    "aliases": [
      "AFL",
      "AFLAC INC"
    ]
  },
  {
    "symbol": "A",
    "name": "AGILENT TECHNOLOGIES INC",
    "sector": "healthcare",
    "aliases": [
      "A",
      "AGILENT TECHNOLOGIES INC"
    ]
  },
  {
    "symbol": "APD",
    "name": "AIR PRODUCTS & CHEMICALS INC",
    "sector": "materials",
    "aliases": [
      "APD",
      "AIR PRODUCTS & CHEMICALS INC"
    ]
  },
  {
    "symbol": "ABNB",
    "name": "AIRBNB INC-CLASS A",
    "sector": "consumer",
    "aliases": [
      "ABNB",
      "AIRBNB INC-CLASS A"
    ]
  },
  {
    "symbol": "AKAM",
    "name": "AKAMAI TECHNOLOGIES INC",
    "sector": "tech",
    "aliases": [
      "AKAM",
      "AKAMAI TECHNOLOGIES INC"
    ]
  },
  {
    "symbol": "ALB",
    "name": "ALBEMARLE CORP",
    "sector": "materials",
    "aliases": [
      "ALB",
      "ALBEMARLE CORP"
    ]
  },
  {
    "symbol": "ARE",
    "name": "Alexandria Real Estate Equities",
    "sector": "realestate",
    "aliases": [
      "ARE",
      "Alexandria Real Estate Equities"
    ]
  },
  {
    "symbol": "ALGN",
    "name": "ALIGN TECHNOLOGY INC",
    "sector": "healthcare",
    "aliases": [
      "ALGN",
      "ALIGN TECHNOLOGY INC"
    ]
  },
  {
    "symbol": "ALLE",
    "name": "ALLEGION PLC",
    "sector": "industrials",
    "aliases": [
      "ALLE",
      "ALLEGION",
      "ALLEGION PLC"
    ]
  },
  {
    "symbol": "LNT",
    "name": "ALLIANT ENERGY CORP",
    "sector": "utilities",
    "aliases": [
      "LNT",
      "ALLIANT ENERGY CORP"
    ]
  },
  {
    "symbol": "ALL",
    "name": "ALLSTATE CORP",
    "sector": "finance",
    "aliases": [
      "ALL",
      "ALLSTATE CORP"
    ]
  },
  {
    "symbol": "GOOGL",
    "name": "ALPHABET INC-CL A",
    "sector": "telecom",
    "aliases": [
      "GOOGL",
      "ALPHABET INC-CL A"
    ]
  },
  {
    "symbol": "GOOG",
    "name": "ALPHABET INC-CL C",
    "sector": "telecom",
    "aliases": [
      "GOOG",
      "ALPHABET INC-CL C"
    ]
  },
  {
    "symbol": "MO",
    "name": "ALTRIA GROUP INC",
    "sector": "consumer",
    "aliases": [
      "MO",
      "ALTRIA INC",
      "ALTRIA GROUP INC"
    ]
  },
  {
    "symbol": "AMZN",
    "name": "AMAZON.COM INC",
    "sector": "consumer",
    "aliases": [
      "AMZN",
      "AMAZON.COM INC"
    ]
  },
  {
    "symbol": "AMCR",
    "name": "AMCOR PLC",
    "sector": "materials",
    "aliases": [
      "AMCR",
      "AMCOR",
      "AMCOR PLC"
    ]
  },
  {
    "symbol": "AEE",
    "name": "AMEREN CORPORATION",
    "sector": "utilities",
    "aliases": [
      "AEE",
      "AMEREN",
      "AMEREN CORPORATION"
    ]
  },
  {
    "symbol": "AEP",
    "name": "AMERICAN ELECTRIC POWER",
    "sector": "utilities",
    "aliases": [
      "AEP",
      "AMERICAN ELECTRIC POWER"
    ]
  },
  {
    "symbol": "AXP",
    "name": "AMERICAN EXPRESS CO",
    "sector": "finance",
    "aliases": [
      "AXP",
      "AMERICAN EXPRESS CO"
    ]
  },
  {
    "symbol": "AIG",
    "name": "AMERICAN INTERNATIONAL GROUP",
    "sector": "finance",
    "aliases": [
      "AIG",
      "AMERICAN INTERNATIONAL",
      "AMERICAN INTERNATIONAL GROUP"
    ]
  },
  {
    "symbol": "AMT",
    "name": "American Tower",
    "sector": "realestate",
    "aliases": [
      "AMT",
      "American Tower"
    ]
  },
  {
    "symbol": "AWK",
    "name": "AMERICAN WATER WORKS CO INC",
    "sector": "utilities",
    "aliases": [
      "AWK",
      "AMERICAN WATER WORKS CO INC"
    ]
  },
  {
    "symbol": "AMP",
    "name": "AMERIPRISE FINANCIAL INC",
    "sector": "finance",
    "aliases": [
      "AMP",
      "AMERIPRISE FINANCIAL INC"
    ]
  },
  {
    "symbol": "AME",
    "name": "AMETEK INC",
    "sector": "industrials",
    "aliases": [
      "AME",
      "AMETEK INC"
    ]
  },
  {
    "symbol": "AMGN",
    "name": "AMGEN INC",
    "sector": "healthcare",
    "aliases": [
      "AMGN",
      "AMGEN INC"
    ]
  },
  {
    "symbol": "APH",
    "name": "AMPHENOL CORP-CL A",
    "sector": "tech",
    "aliases": [
      "APH",
      "AMPHENOL CORP-CL A"
    ]
  },
  {
    "symbol": "ADI",
    "name": "ANALOG DEVICES INC",
    "sector": "tech",
    "aliases": [
      "ADI",
      "ANALOG DEVICES INC"
    ]
  },
  {
    "symbol": "AON",
    "name": "AON PLC-CLASS A",
    "sector": "finance",
    "aliases": [
      "AON",
      "AON-CLASS A",
      "AON PLC-CLASS A"
    ]
  },
  {
    "symbol": "APA",
    "name": "APA CORP",
    "sector": "energy",
    "aliases": [
      "APA",
      "APA CORP"
    ]
  },
  {
    "symbol": "APO",
    "name": "APOLLO GLOBAL MANAGEMENT INC",
    "sector": "finance",
    "aliases": [
      "APO",
      "APOLLO GLOBAL MANAGEMENT INC"
    ]
  },
  {
    "symbol": "AAPL",
    "name": "APPLE INC",
    "sector": "tech",
    "aliases": [
      "AAPL",
      "APPLE INC"
    ]
  },
  {
    "symbol": "AMAT",
    "name": "APPLIED MATERIALS INC",
    "sector": "tech",
    "aliases": [
      "AMAT",
      "APPLIED MATERIALS INC"
    ]
  },
  {
    "symbol": "APP",
    "name": "APPLOVIN CORP-CLASS A",
    "sector": "tech",
    "aliases": [
      "APP",
      "APPLOVIN CORP-CLASS A"
    ]
  },
  {
    "symbol": "APTV",
    "name": "APTIV PLC",
    "sector": "consumer",
    "aliases": [
      "APTV",
      "APTIV",
      "APTIV PLC"
    ]
  },
  {
    "symbol": "ACGL",
    "name": "ARCH CAPITAL GROUP LTD",
    "sector": "finance",
    "aliases": [
      "ACGL",
      "ARCH CAPITAL LTD",
      "ARCH CAPITAL GROUP LTD"
    ]
  },
  {
    "symbol": "ADM",
    "name": "ARCHER-DANIELS-MIDLAND CO",
    "sector": "consumer",
    "aliases": [
      "ADM",
      "ARCHER-DANIELS-MIDLAND CO"
    ]
  },
  {
    "symbol": "ARES",
    "name": "ARES MANAGEMENT CORP - A",
    "sector": "finance",
    "aliases": [
      "ARES",
      "ARES MANAGEMENT CORP - A"
    ]
  },
  {
    "symbol": "ANET",
    "name": "ARISTA NETWORKS INC",
    "sector": "tech",
    "aliases": [
      "ANET",
      "ARISTA NETWORKS INC"
    ]
  },
  {
    "symbol": "AJG",
    "name": "ARTHUR J GALLAGHER & CO",
    "sector": "finance",
    "aliases": [
      "AJG",
      "ARTHUR J GALLAGHER & CO"
    ]
  },
  {
    "symbol": "AIZ",
    "name": "ASSURANT INC",
    "sector": "finance",
    "aliases": [
      "AIZ",
      "ASSURANT INC"
    ]
  },
  {
    "symbol": "T",
    "name": "AT&T INC",
    "sector": "telecom",
    "aliases": [
      "T",
      "AT&T INC"
    ]
  },
  {
    "symbol": "ATO",
    "name": "ATMOS ENERGY CORP",
    "sector": "utilities",
    "aliases": [
      "ATO",
      "ATMOS ENERGY CORP"
    ]
  },
  {
    "symbol": "ADSK",
    "name": "AUTODESK INC",
    "sector": "tech",
    "aliases": [
      "ADSK",
      "AUTODESK INC"
    ]
  },
  {
    "symbol": "ADP",
    "name": "AUTOMATIC DATA PROCESSING",
    "sector": "industrials",
    "aliases": [
      "ADP",
      "AUTOMATIC DATA PROCESSING"
    ]
  },
  {
    "symbol": "AZO",
    "name": "AUTOZONE INC",
    "sector": "consumer",
    "aliases": [
      "AZO",
      "AUTOZONE INC"
    ]
  },
  {
    "symbol": "AVB",
    "name": "AvalonBay Communities",
    "sector": "realestate",
    "aliases": [
      "AVB",
      "AvalonBay Communities"
    ]
  },
  {
    "symbol": "AVY",
    "name": "AVERY DENNISON CORP",
    "sector": "materials",
    "aliases": [
      "AVY",
      "AVERY DENNISON CORP"
    ]
  },
  {
    "symbol": "AXON",
    "name": "AXON ENTERPRISE INC",
    "sector": "industrials",
    "aliases": [
      "AXON",
      "AXON ENTERPRISE INC"
    ]
  },
  {
    "symbol": "BKR",
    "name": "BAKER HUGHES CO",
    "sector": "energy",
    "aliases": [
      "BKR",
      "BAKER HUGHES CO"
    ]
  },
  {
    "symbol": "BALL",
    "name": "BALL CORP",
    "sector": "materials",
    "aliases": [
      "BALL",
      "BALL CORP"
    ]
  },
  {
    "symbol": "BAC",
    "name": "BANK OF AMERICA CORP",
    "sector": "finance",
    "aliases": [
      "BAC",
      "BANK OF AMERICA CORP"
    ]
  },
  {
    "symbol": "BAX",
    "name": "BAXTER INTERNATIONAL INC",
    "sector": "healthcare",
    "aliases": [
      "BAX",
      "BAXTER INTERNATIONAL INC"
    ]
  },
  {
    "symbol": "BDX",
    "name": "BECTON DICKINSON AND CO",
    "sector": "healthcare",
    "aliases": [
      "BDX",
      "BECTON DICKINSON AND CO"
    ]
  },
  {
    "symbol": "BRK.B",
    "name": "BERKSHIRE HATHAWAY INC-CL B",
    "sector": "finance",
    "aliases": [
      "BRK.B",
      "BERKSHIRE HATHAWAY INC-CL B"
    ]
  },
  {
    "symbol": "BBY",
    "name": "BEST BUY CO INC",
    "sector": "consumer",
    "aliases": [
      "BBY",
      "BEST BUY CO INC"
    ]
  },
  {
    "symbol": "TECH",
    "name": "BIO-TECHNE CORP",
    "sector": "healthcare",
    "aliases": [
      "TECH",
      "BIO-TECHNE CORP"
    ]
  },
  {
    "symbol": "BIIB",
    "name": "BIOGEN INC",
    "sector": "healthcare",
    "aliases": [
      "BIIB",
      "BIOGEN INC"
    ]
  },
  {
    "symbol": "BLK",
    "name": "BLACKROCK INC",
    "sector": "finance",
    "aliases": [
      "BLK",
      "BLACKROCK INC"
    ]
  },
  {
    "symbol": "BX",
    "name": "BLACKSTONE INC",
    "sector": "finance",
    "aliases": [
      "BX",
      "BLACKSTONE INC"
    ]
  },
  {
    "symbol": "XYZ",
    "name": "BLOCK INC",
    "sector": "tech",
    "aliases": [
      "XYZ",
      "BLOCK INC"
    ]
  },
  {
    "symbol": "BNY",
    "name": "BANK OF NEW YORK MELLON CORP",
    "sector": "finance",
    "aliases": [
      "BNY",
      "BANK OF NEW YORK MELLON CORP"
    ]
  },
  {
    "symbol": "BA",
    "name": "BOEING CO/THE",
    "sector": "industrials",
    "aliases": [
      "BA",
      "BOEING CO/THE"
    ]
  },
  {
    "symbol": "BKNG",
    "name": "BOOKING HOLDINGS INC",
    "sector": "consumer",
    "aliases": [
      "BKNG",
      "BOOKING INC",
      "BOOKING HOLDINGS INC"
    ]
  },
  {
    "symbol": "BSX",
    "name": "BOSTON SCIENTIFIC CORP",
    "sector": "healthcare",
    "aliases": [
      "BSX",
      "BOSTON SCIENTIFIC CORP"
    ]
  },
  {
    "symbol": "BMY",
    "name": "BRISTOL-MYERS SQUIBB CO",
    "sector": "healthcare",
    "aliases": [
      "BMY",
      "BRISTOL-MYERS SQUIBB CO"
    ]
  },
  {
    "symbol": "AVGO",
    "name": "BROADCOM INC",
    "sector": "tech",
    "aliases": [
      "AVGO",
      "BROADCOM INC"
    ]
  },
  {
    "symbol": "BR",
    "name": "BROADRIDGE FINANCIAL SOLUTIO",
    "sector": "industrials",
    "aliases": [
      "BR",
      "BROADRIDGE FINANCIAL SOLUTIO"
    ]
  },
  {
    "symbol": "BRO",
    "name": "BROWN & BROWN INC",
    "sector": "finance",
    "aliases": [
      "BRO",
      "BROWN & BROWN INC"
    ]
  },
  {
    "symbol": "BF.B",
    "name": "BROWN-FORMAN CORP-CLASS B",
    "sector": "consumer",
    "aliases": [
      "BF.B",
      "BROWN-FORMAN CORP-CLASS B"
    ]
  },
  {
    "symbol": "BLDR",
    "name": "BUILDERS FIRSTSOURCE INC",
    "sector": "industrials",
    "aliases": [
      "BLDR",
      "BUILDERS FIRSTSOURCE INC"
    ]
  },
  {
    "symbol": "BG",
    "name": "BUNGE GLOBAL SA",
    "sector": "consumer",
    "aliases": [
      "BG",
      "BUNGE GLOBAL SA"
    ]
  },
  {
    "symbol": "BXP",
    "name": "BXP",
    "sector": "tech",
    "aliases": [
      "BXP"
    ]
  },
  {
    "symbol": "CHRW",
    "name": "C.H. ROBINSON WORLDWIDE INC",
    "sector": "industrials",
    "aliases": [
      "CHRW",
      "C.H. ROBINSON WORLDWIDE INC"
    ]
  },
  {
    "symbol": "CDNS",
    "name": "CADENCE DESIGN SYS INC",
    "sector": "tech",
    "aliases": [
      "CDNS",
      "CADENCE DESIGN SYS INC"
    ]
  },
  {
    "symbol": "CPT",
    "name": "Camden Property Trust",
    "sector": "realestate",
    "aliases": [
      "CPT",
      "Camden Property Trust"
    ]
  },
  {
    "symbol": "COF",
    "name": "CAPITAL ONE FINANCIAL CORP",
    "sector": "finance",
    "aliases": [
      "COF",
      "CAPITAL ONE FINANCIAL CORP"
    ]
  },
  {
    "symbol": "CAH",
    "name": "CARDINAL HEALTH INC",
    "sector": "healthcare",
    "aliases": [
      "CAH",
      "CARDINAL HEALTH INC"
    ]
  },
  {
    "symbol": "CCL",
    "name": "CARNIVAL CORP LTD",
    "sector": "consumer",
    "aliases": [
      "CCL",
      "CARNIVAL CORP LTD"
    ]
  },
  {
    "symbol": "CARR",
    "name": "CARRIER GLOBAL CORP",
    "sector": "industrials",
    "aliases": [
      "CARR",
      "CARRIER GLOBAL CORP"
    ]
  },
  {
    "symbol": "CVNA",
    "name": "CARVANA CO",
    "sector": "consumer",
    "aliases": [
      "CVNA",
      "CARVANA CO"
    ]
  },
  {
    "symbol": "CASY",
    "name": "CASEY'S GENERAL STORES INC",
    "sector": "consumer",
    "aliases": [
      "CASY",
      "CASEY'S GENERAL STORES INC"
    ]
  },
  {
    "symbol": "CAT",
    "name": "CATERPILLAR INC",
    "sector": "industrials",
    "aliases": [
      "CAT",
      "CATERPILLAR INC"
    ]
  },
  {
    "symbol": "CBOE",
    "name": "Cboe Global Markets",
    "sector": "finance",
    "aliases": [
      "CBOE",
      "Cboe Global Markets"
    ]
  },
  {
    "symbol": "CBRE",
    "name": "CBRE GROUP INC - A",
    "sector": "realestate",
    "aliases": [
      "CBRE",
      "CBRE INC - A",
      "CBRE GROUP INC - A"
    ]
  },
  {
    "symbol": "CDW",
    "name": "CDW CORP/DE",
    "sector": "tech",
    "aliases": [
      "CDW",
      "CDW CORP/DE"
    ]
  },
  {
    "symbol": "COR",
    "name": "CENCORA INC",
    "sector": "healthcare",
    "aliases": [
      "COR",
      "CENCORA INC"
    ]
  },
  {
    "symbol": "CNC",
    "name": "CENTENE CORP",
    "sector": "healthcare",
    "aliases": [
      "CNC",
      "CENTENE CORP"
    ]
  },
  {
    "symbol": "CNP",
    "name": "CENTERPOINT ENERGY INC",
    "sector": "utilities",
    "aliases": [
      "CNP",
      "CENTERPOINT ENERGY INC"
    ]
  },
  {
    "symbol": "CF",
    "name": "CF INDUSTRIES HOLDINGS INC",
    "sector": "materials",
    "aliases": [
      "CF",
      "CF INDUSTRIES INC",
      "CF INDUSTRIES HOLDINGS INC"
    ]
  },
  {
    "symbol": "CRL",
    "name": "CHARLES RIVER LABORATORIES",
    "sector": "healthcare",
    "aliases": [
      "CRL",
      "CHARLES RIVER LABORATORIES"
    ]
  },
  {
    "symbol": "SCHW",
    "name": "SCHWAB (CHARLES) CORP",
    "sector": "finance",
    "aliases": [
      "SCHW",
      "SCHWAB (CHARLES) CORP"
    ]
  },
  {
    "symbol": "CHTR",
    "name": "CHARTER COMMUNICATIONS INC-A",
    "sector": "telecom",
    "aliases": [
      "CHTR",
      "CHARTER COMMUNICATIONS INC-A"
    ]
  },
  {
    "symbol": "CVX",
    "name": "CHEVRON CORP",
    "sector": "energy",
    "aliases": [
      "CVX",
      "CHEVRON CORP"
    ]
  },
  {
    "symbol": "CMG",
    "name": "CHIPOTLE MEXICAN GRILL INC",
    "sector": "consumer",
    "aliases": [
      "CMG",
      "CHIPOTLE MEXICAN GRILL INC"
    ]
  },
  {
    "symbol": "CB",
    "name": "CHUBB LTD",
    "sector": "finance",
    "aliases": [
      "CB",
      "CHUBB LTD"
    ]
  },
  {
    "symbol": "CHD",
    "name": "CHURCH & DWIGHT CO INC",
    "sector": "consumer",
    "aliases": [
      "CHD",
      "CHURCH & DWIGHT CO INC"
    ]
  },
  {
    "symbol": "CIEN",
    "name": "CIENA CORP",
    "sector": "tech",
    "aliases": [
      "CIEN",
      "CIENA CORP"
    ]
  },
  {
    "symbol": "CI",
    "name": "THE CIGNA GROUP",
    "sector": "healthcare",
    "aliases": [
      "CI",
      "THE CIGNA",
      "THE CIGNA GROUP"
    ]
  },
  {
    "symbol": "CINF",
    "name": "CINCINNATI FINANCIAL CORP",
    "sector": "finance",
    "aliases": [
      "CINF",
      "CINCINNATI FINANCIAL CORP"
    ]
  },
  {
    "symbol": "CTAS",
    "name": "CINTAS CORP",
    "sector": "industrials",
    "aliases": [
      "CTAS",
      "CINTAS CORP"
    ]
  },
  {
    "symbol": "CSCO",
    "name": "CISCO SYSTEMS INC",
    "sector": "tech",
    "aliases": [
      "CSCO",
      "CISCO SYSTEMS INC"
    ]
  },
  {
    "symbol": "C",
    "name": "CITIGROUP INC",
    "sector": "finance",
    "aliases": [
      "C",
      "CITIGROUP INC"
    ]
  },
  {
    "symbol": "CFG",
    "name": "CITIZENS FINANCIAL GROUP",
    "sector": "finance",
    "aliases": [
      "CFG",
      "CITIZENS FINANCIAL",
      "CITIZENS FINANCIAL GROUP"
    ]
  },
  {
    "symbol": "CLX",
    "name": "CLOROX COMPANY",
    "sector": "consumer",
    "aliases": [
      "CLX",
      "CLOROX",
      "CLOROX COMPANY"
    ]
  },
  {
    "symbol": "CME",
    "name": "CME GROUP INC",
    "sector": "finance",
    "aliases": [
      "CME",
      "CME INC",
      "CME GROUP INC"
    ]
  },
  {
    "symbol": "CMS",
    "name": "CMS ENERGY CORP",
    "sector": "utilities",
    "aliases": [
      "CMS",
      "CMS ENERGY CORP"
    ]
  },
  {
    "symbol": "KO",
    "name": "COCA-COLA CO/THE",
    "sector": "consumer",
    "aliases": [
      "KO",
      "COCA-COLA CO/THE"
    ]
  },
  {
    "symbol": "CTSH",
    "name": "COGNIZANT TECH SOLUTIONS-A",
    "sector": "tech",
    "aliases": [
      "CTSH",
      "COGNIZANT TECH SOLUTIONS-A"
    ]
  },
  {
    "symbol": "COHR",
    "name": "COHERENT CORP",
    "sector": "tech",
    "aliases": [
      "COHR",
      "COHERENT CORP"
    ]
  },
  {
    "symbol": "COIN",
    "name": "COINBASE GLOBAL INC -CLASS A",
    "sector": "finance",
    "aliases": [
      "COIN",
      "COINBASE GLOBAL INC -CLASS A"
    ]
  },
  {
    "symbol": "CL",
    "name": "COLGATE-PALMOLIVE CO",
    "sector": "consumer",
    "aliases": [
      "CL",
      "COLGATE-PALMOLIVE CO"
    ]
  },
  {
    "symbol": "CMCSA",
    "name": "COMCAST CORP-CLASS A",
    "sector": "telecom",
    "aliases": [
      "CMCSA",
      "COMCAST CORP-CLASS A"
    ]
  },
  {
    "symbol": "FIX",
    "name": "COMFORT SYSTEMS USA INC",
    "sector": "industrials",
    "aliases": [
      "FIX",
      "COMFORT SYSTEMS USA INC"
    ]
  },
  {
    "symbol": "COP",
    "name": "CONOCOPHILLIPS",
    "sector": "energy",
    "aliases": [
      "COP",
      "CONOCOPHILLIPS"
    ]
  },
  {
    "symbol": "ED",
    "name": "CONSOLIDATED EDISON INC",
    "sector": "utilities",
    "aliases": [
      "ED",
      "CONSOLIDATED EDISON INC"
    ]
  },
  {
    "symbol": "STZ",
    "name": "CONSTELLATION BRANDS INC-A",
    "sector": "consumer",
    "aliases": [
      "STZ",
      "CONSTELLATION BRANDS INC-A"
    ]
  },
  {
    "symbol": "CEG",
    "name": "CONSTELLATION ENERGY",
    "sector": "utilities",
    "aliases": [
      "CEG",
      "CONSTELLATION ENERGY"
    ]
  },
  {
    "symbol": "COO",
    "name": "COOPER COS INC/THE",
    "sector": "healthcare",
    "aliases": [
      "COO",
      "COOPER COS INC/THE"
    ]
  },
  {
    "symbol": "CPRT",
    "name": "COPART INC",
    "sector": "industrials",
    "aliases": [
      "CPRT",
      "COPART INC"
    ]
  },
  {
    "symbol": "GLW",
    "name": "CORNING INC",
    "sector": "tech",
    "aliases": [
      "GLW",
      "CORNING INC"
    ]
  },
  {
    "symbol": "CPAY",
    "name": "CORPAY INC",
    "sector": "finance",
    "aliases": [
      "CPAY",
      "CORPAY INC"
    ]
  },
  {
    "symbol": "CTVA",
    "name": "CORTEVA INC",
    "sector": "materials",
    "aliases": [
      "CTVA",
      "CORTEVA INC"
    ]
  },
  {
    "symbol": "CSGP",
    "name": "COSTAR GROUP INC",
    "sector": "realestate",
    "aliases": [
      "CSGP",
      "COSTAR INC",
      "COSTAR GROUP INC"
    ]
  },
  {
    "symbol": "COST",
    "name": "COSTCO WHOLESALE CORP",
    "sector": "consumer",
    "aliases": [
      "COST",
      "COSTCO WHOLESALE CORP"
    ]
  },
  {
    "symbol": "CRH",
    "name": "CRH PLC",
    "sector": "materials",
    "aliases": [
      "CRH",
      "CRH PLC"
    ]
  },
  {
    "symbol": "CRWD",
    "name": "CROWDSTRIKE HOLDINGS INC - A",
    "sector": "tech",
    "aliases": [
      "CRWD",
      "CROWDSTRIKE INC - A",
      "CROWDSTRIKE HOLDINGS INC - A"
    ]
  },
  {
    "symbol": "CCI",
    "name": "Crown Castle",
    "sector": "realestate",
    "aliases": [
      "CCI",
      "Crown Castle"
    ]
  },
  {
    "symbol": "CSX",
    "name": "CSX CORP",
    "sector": "industrials",
    "aliases": [
      "CSX",
      "CSX CORP"
    ]
  },
  {
    "symbol": "CMI",
    "name": "CUMMINS INC",
    "sector": "industrials",
    "aliases": [
      "CMI",
      "CUMMINS INC"
    ]
  },
  {
    "symbol": "CVS",
    "name": "CVS HEALTH CORP",
    "sector": "healthcare",
    "aliases": [
      "CVS",
      "CVS HEALTH CORP"
    ]
  },
  {
    "symbol": "DHR",
    "name": "DANAHER CORP",
    "sector": "healthcare",
    "aliases": [
      "DHR",
      "DANAHER CORP"
    ]
  },
  {
    "symbol": "DRI",
    "name": "DARDEN RESTAURANTS INC",
    "sector": "consumer",
    "aliases": [
      "DRI",
      "DARDEN RESTAURANTS INC"
    ]
  },
  {
    "symbol": "DDOG",
    "name": "DATADOG INC - CLASS A",
    "sector": "tech",
    "aliases": [
      "DDOG",
      "DATADOG INC - CLASS A"
    ]
  },
  {
    "symbol": "DVA",
    "name": "DAVITA INC",
    "sector": "healthcare",
    "aliases": [
      "DVA",
      "DAVITA INC"
    ]
  },
  {
    "symbol": "DECK",
    "name": "DECKERS OUTDOOR CORP",
    "sector": "consumer",
    "aliases": [
      "DECK",
      "DECKERS OUTDOOR CORP"
    ]
  },
  {
    "symbol": "DE",
    "name": "DEERE & CO",
    "sector": "industrials",
    "aliases": [
      "DE",
      "DEERE & CO"
    ]
  },
  {
    "symbol": "DELL",
    "name": "DELL TECHNOLOGIES -C",
    "sector": "tech",
    "aliases": [
      "DELL",
      "DELL TECHNOLOGIES -C"
    ]
  },
  {
    "symbol": "DAL",
    "name": "DELTA AIR LINES INC",
    "sector": "industrials",
    "aliases": [
      "DAL",
      "DELTA AIR LINES INC"
    ]
  },
  {
    "symbol": "DVN",
    "name": "DEVON ENERGY CORP",
    "sector": "energy",
    "aliases": [
      "DVN",
      "DEVON ENERGY CORP"
    ]
  },
  {
    "symbol": "DXCM",
    "name": "DEXCOM INC",
    "sector": "healthcare",
    "aliases": [
      "DXCM",
      "DEXCOM INC"
    ]
  },
  {
    "symbol": "FANG",
    "name": "DIAMONDBACK ENERGY INC",
    "sector": "energy",
    "aliases": [
      "FANG",
      "DIAMONDBACK ENERGY INC"
    ]
  },
  {
    "symbol": "DLR",
    "name": "Digital Realty",
    "sector": "realestate",
    "aliases": [
      "DLR",
      "Digital Realty"
    ]
  },
  {
    "symbol": "DG",
    "name": "DOLLAR GENERAL CORP",
    "sector": "consumer",
    "aliases": [
      "DG",
      "DOLLAR GENERAL CORP"
    ]
  },
  {
    "symbol": "DLTR",
    "name": "DOLLAR TREE INC",
    "sector": "consumer",
    "aliases": [
      "DLTR",
      "DOLLAR TREE INC"
    ]
  },
  {
    "symbol": "D",
    "name": "DOMINION ENERGY INC",
    "sector": "utilities",
    "aliases": [
      "D",
      "DOMINION ENERGY INC"
    ]
  },
  {
    "symbol": "DPZ",
    "name": "DOMINO'S PIZZA INC",
    "sector": "consumer",
    "aliases": [
      "DPZ",
      "DOMINO'S PIZZA INC"
    ]
  },
  {
    "symbol": "DASH",
    "name": "DOORDASH INC - A",
    "sector": "consumer",
    "aliases": [
      "DASH",
      "DOORDASH INC - A"
    ]
  },
  {
    "symbol": "DOV",
    "name": "DOVER CORP",
    "sector": "industrials",
    "aliases": [
      "DOV",
      "DOVER CORP"
    ]
  },
  {
    "symbol": "DOW",
    "name": "DOW INC",
    "sector": "materials",
    "aliases": [
      "DOW",
      "DOW INC"
    ]
  },
  {
    "symbol": "DHI",
    "name": "DR HORTON INC",
    "sector": "consumer",
    "aliases": [
      "DHI",
      "DR HORTON INC"
    ]
  },
  {
    "symbol": "DTE",
    "name": "DTE ENERGY COMPANY",
    "sector": "utilities",
    "aliases": [
      "DTE",
      "DTE ENERGY",
      "DTE ENERGY COMPANY"
    ]
  },
  {
    "symbol": "DUK",
    "name": "DUKE ENERGY CORP",
    "sector": "utilities",
    "aliases": [
      "DUK",
      "DUKE ENERGY CORP"
    ]
  },
  {
    "symbol": "DD",
    "name": "DUPONT DE NEMOURS INC",
    "sector": "materials",
    "aliases": [
      "DD",
      "DUPONT DE NEMOURS INC"
    ]
  },
  {
    "symbol": "ETN",
    "name": "EATON CORP PLC",
    "sector": "industrials",
    "aliases": [
      "ETN",
      "EATON CORP",
      "EATON CORP PLC"
    ]
  },
  {
    "symbol": "EBAY",
    "name": "EBAY INC",
    "sector": "consumer",
    "aliases": [
      "EBAY",
      "EBAY INC"
    ]
  },
  {
    "symbol": "ECHO",
    "name": "ECHOSTAR CORP-A",
    "sector": "telecom",
    "aliases": [
      "ECHO",
      "ECHOSTAR CORP-A"
    ]
  },
  {
    "symbol": "ECL",
    "name": "ECOLAB INC",
    "sector": "materials",
    "aliases": [
      "ECL",
      "ECOLAB INC"
    ]
  },
  {
    "symbol": "EIX",
    "name": "EDISON INTERNATIONAL",
    "sector": "utilities",
    "aliases": [
      "EIX",
      "EDISON INTERNATIONAL"
    ]
  },
  {
    "symbol": "EW",
    "name": "EDWARDS LIFESCIENCES CORP",
    "sector": "healthcare",
    "aliases": [
      "EW",
      "EDWARDS LIFESCIENCES CORP"
    ]
  },
  {
    "symbol": "EA",
    "name": "Electronic Arts",
    "sector": "telecom",
    "aliases": [
      "EA",
      "Electronic Arts"
    ]
  },
  {
    "symbol": "ELV",
    "name": "ELEVANCE HEALTH INC",
    "sector": "healthcare",
    "aliases": [
      "ELV",
      "ELEVANCE HEALTH INC"
    ]
  },
  {
    "symbol": "EME",
    "name": "EMCOR GROUP INC",
    "sector": "industrials",
    "aliases": [
      "EME",
      "EMCOR INC",
      "EMCOR GROUP INC"
    ]
  },
  {
    "symbol": "EMR",
    "name": "EMERSON ELECTRIC CO",
    "sector": "industrials",
    "aliases": [
      "EMR",
      "EMERSON ELECTRIC CO"
    ]
  },
  {
    "symbol": "ETR",
    "name": "ENTERGY CORP",
    "sector": "utilities",
    "aliases": [
      "ETR",
      "ENTERGY CORP"
    ]
  },
  {
    "symbol": "EOG",
    "name": "EOG RESOURCES INC",
    "sector": "energy",
    "aliases": [
      "EOG",
      "EOG RESOURCES INC"
    ]
  },
  {
    "symbol": "EQT",
    "name": "EQT CORP",
    "sector": "energy",
    "aliases": [
      "EQT",
      "EQT CORP"
    ]
  },
  {
    "symbol": "EFX",
    "name": "EQUIFAX INC",
    "sector": "industrials",
    "aliases": [
      "EFX",
      "EQUIFAX INC"
    ]
  },
  {
    "symbol": "EQIX",
    "name": "Equinix",
    "sector": "realestate",
    "aliases": [
      "EQIX",
      "Equinix"
    ]
  },
  {
    "symbol": "EQR",
    "name": "Equity Residential",
    "sector": "realestate",
    "aliases": [
      "EQR",
      "Equity Residential"
    ]
  },
  {
    "symbol": "ERIE",
    "name": "ERIE INDEMNITY COMPANY-CL A",
    "sector": "finance",
    "aliases": [
      "ERIE",
      "ERIE INDEMNITY-CL A",
      "ERIE INDEMNITY COMPANY-CL A"
    ]
  },
  {
    "symbol": "ESS",
    "name": "Essex Property Trust",
    "sector": "realestate",
    "aliases": [
      "ESS",
      "Essex Property Trust"
    ]
  },
  {
    "symbol": "EL",
    "name": "ESTEE LAUDER COMPANIES-CL A",
    "sector": "consumer",
    "aliases": [
      "EL",
      "ESTEE LAUDER COMPANIES-CL A"
    ]
  },
  {
    "symbol": "EG",
    "name": "EVEREST GROUP LTD",
    "sector": "finance",
    "aliases": [
      "EG",
      "EVEREST LTD",
      "EVEREST GROUP LTD"
    ]
  },
  {
    "symbol": "EVRG",
    "name": "EVERGY INC",
    "sector": "utilities",
    "aliases": [
      "EVRG",
      "EVERGY INC"
    ]
  },
  {
    "symbol": "ES",
    "name": "EVERSOURCE ENERGY",
    "sector": "utilities",
    "aliases": [
      "ES",
      "EVERSOURCE ENERGY"
    ]
  },
  {
    "symbol": "EXC",
    "name": "EXELON CORP",
    "sector": "utilities",
    "aliases": [
      "EXC",
      "EXELON CORP"
    ]
  },
  {
    "symbol": "EXE",
    "name": "EXPAND ENERGY CORP",
    "sector": "energy",
    "aliases": [
      "EXE",
      "EXPAND ENERGY CORP"
    ]
  },
  {
    "symbol": "EXPE",
    "name": "EXPEDIA GROUP INC",
    "sector": "consumer",
    "aliases": [
      "EXPE",
      "EXPEDIA INC",
      "EXPEDIA GROUP INC"
    ]
  },
  {
    "symbol": "EXPD",
    "name": "EXPEDITORS INTL WASH INC",
    "sector": "industrials",
    "aliases": [
      "EXPD",
      "EXPEDITORS INTL WASH INC"
    ]
  },
  {
    "symbol": "EXR",
    "name": "Extra Space Storage",
    "sector": "realestate",
    "aliases": [
      "EXR",
      "Extra Space Storage"
    ]
  },
  {
    "symbol": "XOM",
    "name": "EXXONMOBIL HOLDINGS CORP",
    "sector": "energy",
    "aliases": [
      "XOM",
      "EXXONMOBIL CORP",
      "EXXONMOBIL HOLDINGS CORP"
    ]
  },
  {
    "symbol": "FFIV",
    "name": "F5 INC",
    "sector": "tech",
    "aliases": [
      "FFIV",
      "F5 INC"
    ]
  },
  {
    "symbol": "FDS",
    "name": "FACTSET RESEARCH SYSTEMS INC",
    "sector": "finance",
    "aliases": [
      "FDS",
      "FACTSET RESEARCH SYSTEMS INC"
    ]
  },
  {
    "symbol": "FICO",
    "name": "FAIR ISAAC CORP",
    "sector": "tech",
    "aliases": [
      "FICO",
      "FAIR ISAAC CORP"
    ]
  },
  {
    "symbol": "FAST",
    "name": "FASTENAL CO",
    "sector": "industrials",
    "aliases": [
      "FAST",
      "FASTENAL CO"
    ]
  },
  {
    "symbol": "FRT",
    "name": "Federal Realty Investment Trust",
    "sector": "realestate",
    "aliases": [
      "FRT",
      "Federal Realty Investment Trust"
    ]
  },
  {
    "symbol": "FDX",
    "name": "FEDEX CORP",
    "sector": "industrials",
    "aliases": [
      "FDX",
      "FEDEX CORP"
    ]
  },
  {
    "symbol": "FDXF",
    "name": "FEDEX FREIGHT HOLDING CO",
    "sector": "industrials",
    "aliases": [
      "FDXF",
      "FEDEX FREIGHT HOLDING CO"
    ]
  },
  {
    "symbol": "FIS",
    "name": "FIDELITY NATIONAL INFO SERV",
    "sector": "finance",
    "aliases": [
      "FIS",
      "FIDELITY NATIONAL INFO SERV"
    ]
  },
  {
    "symbol": "FITB",
    "name": "FIFTH THIRD BANCORP",
    "sector": "finance",
    "aliases": [
      "FITB",
      "FIFTH THIRD BANCORP"
    ]
  },
  {
    "symbol": "FSLR",
    "name": "FIRST SOLAR INC",
    "sector": "tech",
    "aliases": [
      "FSLR",
      "FIRST SOLAR INC"
    ]
  },
  {
    "symbol": "FE",
    "name": "FIRSTENERGY CORP",
    "sector": "utilities",
    "aliases": [
      "FE",
      "FIRSTENERGY CORP"
    ]
  },
  {
    "symbol": "FISV",
    "name": "FISERV INC",
    "sector": "finance",
    "aliases": [
      "FISV",
      "FISERV INC"
    ]
  },
  {
    "symbol": "FLEX",
    "name": "FLEX LTD",
    "sector": "tech",
    "aliases": [
      "FLEX",
      "FLEX LTD"
    ]
  },
  {
    "symbol": "F",
    "name": "FORD MOTOR CO",
    "sector": "consumer",
    "aliases": [
      "F",
      "FORD MOTOR CO"
    ]
  },
  {
    "symbol": "FTNT",
    "name": "FORTINET INC",
    "sector": "tech",
    "aliases": [
      "FTNT",
      "FORTINET INC"
    ]
  },
  {
    "symbol": "FTV",
    "name": "FORTIVE CORP",
    "sector": "industrials",
    "aliases": [
      "FTV",
      "FORTIVE CORP"
    ]
  },
  {
    "symbol": "FOXA",
    "name": "FOX CORP - CLASS A",
    "sector": "telecom",
    "aliases": [
      "FOXA",
      "FOX CORP - CLASS A"
    ]
  },
  {
    "symbol": "FOX",
    "name": "FOX CORP - CLASS B",
    "sector": "telecom",
    "aliases": [
      "FOX",
      "FOX CORP - CLASS B"
    ]
  },
  {
    "symbol": "BEN",
    "name": "FRANKLIN RESOURCES INC",
    "sector": "finance",
    "aliases": [
      "BEN",
      "FRANKLIN RESOURCES INC"
    ]
  },
  {
    "symbol": "FCX",
    "name": "FREEPORT-MCMORAN INC",
    "sector": "materials",
    "aliases": [
      "FCX",
      "FREEPORT-MCMORAN INC"
    ]
  },
  {
    "symbol": "GRMN",
    "name": "GARMIN LTD",
    "sector": "consumer",
    "aliases": [
      "GRMN",
      "GARMIN LTD"
    ]
  },
  {
    "symbol": "IT",
    "name": "GARTNER INC",
    "sector": "tech",
    "aliases": [
      "IT",
      "GARTNER INC"
    ]
  },
  {
    "symbol": "GE",
    "name": "GENERAL ELECTRIC",
    "sector": "industrials",
    "aliases": [
      "GE",
      "GENERAL ELECTRIC"
    ]
  },
  {
    "symbol": "GEHC",
    "name": "GE HEALTHCARE TECHNOLOGY",
    "sector": "healthcare",
    "aliases": [
      "GEHC",
      "GE HEALTHCARE TECHNOLOGY"
    ]
  },
  {
    "symbol": "GEV",
    "name": "GE VERNOVA INC",
    "sector": "industrials",
    "aliases": [
      "GEV",
      "GE VERNOVA INC"
    ]
  },
  {
    "symbol": "GEN",
    "name": "GEN DIGITAL INC",
    "sector": "tech",
    "aliases": [
      "GEN",
      "GEN DIGITAL INC"
    ]
  },
  {
    "symbol": "GNRC",
    "name": "GENERAC HOLDINGS INC",
    "sector": "industrials",
    "aliases": [
      "GNRC",
      "GENERAC INC",
      "GENERAC HOLDINGS INC"
    ]
  },
  {
    "symbol": "GD",
    "name": "GENERAL DYNAMICS CORP",
    "sector": "industrials",
    "aliases": [
      "GD",
      "GENERAL DYNAMICS CORP"
    ]
  },
  {
    "symbol": "GIS",
    "name": "GENERAL MILLS INC",
    "sector": "consumer",
    "aliases": [
      "GIS",
      "GENERAL MILLS INC"
    ]
  },
  {
    "symbol": "GM",
    "name": "GENERAL MOTORS CO",
    "sector": "consumer",
    "aliases": [
      "GM",
      "GENERAL MOTORS CO"
    ]
  },
  {
    "symbol": "GPC",
    "name": "GENUINE PARTS CO",
    "sector": "consumer",
    "aliases": [
      "GPC",
      "GENUINE PARTS CO"
    ]
  },
  {
    "symbol": "GILD",
    "name": "GILEAD SCIENCES INC",
    "sector": "healthcare",
    "aliases": [
      "GILD",
      "GILEAD SCIENCES INC"
    ]
  },
  {
    "symbol": "GPN",
    "name": "GLOBAL PAYMENTS INC",
    "sector": "finance",
    "aliases": [
      "GPN",
      "GLOBAL PAYMENTS INC"
    ]
  },
  {
    "symbol": "GL",
    "name": "GLOBE LIFE INC",
    "sector": "finance",
    "aliases": [
      "GL",
      "GLOBE LIFE INC"
    ]
  },
  {
    "symbol": "GDDY",
    "name": "GODADDY INC - CLASS A",
    "sector": "tech",
    "aliases": [
      "GDDY",
      "GODADDY INC - CLASS A"
    ]
  },
  {
    "symbol": "GS",
    "name": "GOLDMAN SACHS GROUP INC",
    "sector": "finance",
    "aliases": [
      "GS",
      "GOLDMAN SACHS INC",
      "GOLDMAN SACHS GROUP INC"
    ]
  },
  {
    "symbol": "HAL",
    "name": "HALLIBURTON CO",
    "sector": "energy",
    "aliases": [
      "HAL",
      "HALLIBURTON CO"
    ]
  },
  {
    "symbol": "HIG",
    "name": "HARTFORD INSURANCE GROUP INC",
    "sector": "finance",
    "aliases": [
      "HIG",
      "HARTFORD INSURANCE INC",
      "HARTFORD INSURANCE GROUP INC"
    ]
  },
  {
    "symbol": "HAS",
    "name": "HASBRO INC",
    "sector": "consumer",
    "aliases": [
      "HAS",
      "HASBRO INC"
    ]
  },
  {
    "symbol": "HCA",
    "name": "HCA HEALTHCARE INC",
    "sector": "healthcare",
    "aliases": [
      "HCA",
      "HCA HEALTHCARE INC"
    ]
  },
  {
    "symbol": "DOC",
    "name": "Healthpeak Properties",
    "sector": "realestate",
    "aliases": [
      "DOC",
      "Healthpeak Properties"
    ]
  },
  {
    "symbol": "HSIC",
    "name": "HENRY SCHEIN INC",
    "sector": "healthcare",
    "aliases": [
      "HSIC",
      "HENRY SCHEIN INC"
    ]
  },
  {
    "symbol": "HSY",
    "name": "HERSHEY CO/THE",
    "sector": "consumer",
    "aliases": [
      "HSY",
      "HERSHEY CO/THE"
    ]
  },
  {
    "symbol": "HPE",
    "name": "HEWLETT PACKARD ENTERPRISE",
    "sector": "tech",
    "aliases": [
      "HPE",
      "HEWLETT PACKARD ENTERPRISE"
    ]
  },
  {
    "symbol": "HLT",
    "name": "HILTON WORLDWIDE HOLDINGS IN",
    "sector": "consumer",
    "aliases": [
      "HLT",
      "HILTON WORLDWIDE IN",
      "HILTON WORLDWIDE HOLDINGS IN"
    ]
  },
  {
    "symbol": "HD",
    "name": "HOME DEPOT INC",
    "sector": "consumer",
    "aliases": [
      "HD",
      "HOME DEPOT INC"
    ]
  },
  {
    "symbol": "HONA",
    "name": "HONEYWELL AEROSPACE INC",
    "sector": "industrials",
    "aliases": [
      "HONA",
      "HONEYWELL AEROSPACE INC"
    ]
  },
  {
    "symbol": "HON",
    "name": "HONEYWELL INTERNATIONAL INC",
    "sector": "industrials",
    "aliases": [
      "HON",
      "HONEYWELL INTERNATIONAL INC"
    ]
  },
  {
    "symbol": "HRL",
    "name": "HORMEL FOODS CORP",
    "sector": "consumer",
    "aliases": [
      "HRL",
      "HORMEL FOODS CORP"
    ]
  },
  {
    "symbol": "HST",
    "name": "Host Hotels & Resorts",
    "sector": "realestate",
    "aliases": [
      "HST",
      "Host Hotels & Resorts"
    ]
  },
  {
    "symbol": "HWM",
    "name": "HOWMET AEROSPACE INC",
    "sector": "industrials",
    "aliases": [
      "HWM",
      "HOWMET AEROSPACE INC"
    ]
  },
  {
    "symbol": "HPQ",
    "name": "HP INC",
    "sector": "tech",
    "aliases": [
      "HPQ",
      "HP INC"
    ]
  },
  {
    "symbol": "HUBB",
    "name": "HUBBELL INC",
    "sector": "industrials",
    "aliases": [
      "HUBB",
      "HUBBELL INC"
    ]
  },
  {
    "symbol": "HUM",
    "name": "HUMANA INC",
    "sector": "healthcare",
    "aliases": [
      "HUM",
      "HUMANA INC"
    ]
  },
  {
    "symbol": "HBAN",
    "name": "HUNTINGTON BANCSHARES INC",
    "sector": "finance",
    "aliases": [
      "HBAN",
      "HUNTINGTON BANCSHARES INC"
    ]
  },
  {
    "symbol": "HII",
    "name": "HUNTINGTON INGALLS INDUSTRIE",
    "sector": "industrials",
    "aliases": [
      "HII",
      "HUNTINGTON INGALLS INDUSTRIE"
    ]
  },
  {
    "symbol": "IBM",
    "name": "INTL BUSINESS MACHINES CORP",
    "sector": "tech",
    "aliases": [
      "IBM",
      "INTL BUSINESS MACHINES CORP"
    ]
  },
  {
    "symbol": "IEX",
    "name": "IDEX CORP",
    "sector": "industrials",
    "aliases": [
      "IEX",
      "IDEX CORP"
    ]
  },
  {
    "symbol": "IDXX",
    "name": "IDEXX LABORATORIES INC",
    "sector": "healthcare",
    "aliases": [
      "IDXX",
      "IDEXX LABORATORIES INC"
    ]
  },
  {
    "symbol": "ITW",
    "name": "ILLINOIS TOOL WORKS",
    "sector": "industrials",
    "aliases": [
      "ITW",
      "ILLINOIS TOOL WORKS"
    ]
  },
  {
    "symbol": "INCY",
    "name": "INCYTE CORP",
    "sector": "healthcare",
    "aliases": [
      "INCY",
      "INCYTE CORP"
    ]
  },
  {
    "symbol": "IR",
    "name": "INGERSOLL-RAND INC",
    "sector": "industrials",
    "aliases": [
      "IR",
      "INGERSOLL-RAND INC"
    ]
  },
  {
    "symbol": "PODD",
    "name": "INSULET CORP",
    "sector": "healthcare",
    "aliases": [
      "PODD",
      "INSULET CORP"
    ]
  },
  {
    "symbol": "INTC",
    "name": "INTEL CORP",
    "sector": "tech",
    "aliases": [
      "INTC",
      "INTEL CORP"
    ]
  },
  {
    "symbol": "IBKR",
    "name": "INTERACTIVE BROKERS GRO-CL A",
    "sector": "finance",
    "aliases": [
      "IBKR",
      "INTERACTIVE BROKERS GRO-CL A"
    ]
  },
  {
    "symbol": "ICE",
    "name": "INTERCONTINENTAL EXCHANGE IN",
    "sector": "finance",
    "aliases": [
      "ICE",
      "INTERCONTINENTAL EXCHANGE IN"
    ]
  },
  {
    "symbol": "IFF",
    "name": "INTL FLAVORS & FRAGRANCES",
    "sector": "materials",
    "aliases": [
      "IFF",
      "INTL FLAVORS & FRAGRANCES"
    ]
  },
  {
    "symbol": "IP",
    "name": "INTERNATIONAL PAPER CO",
    "sector": "materials",
    "aliases": [
      "IP",
      "INTERNATIONAL PAPER CO"
    ]
  },
  {
    "symbol": "INTU",
    "name": "INTUIT INC",
    "sector": "tech",
    "aliases": [
      "INTU",
      "INTUIT INC"
    ]
  },
  {
    "symbol": "ISRG",
    "name": "INTUITIVE SURGICAL INC",
    "sector": "healthcare",
    "aliases": [
      "ISRG",
      "INTUITIVE SURGICAL INC"
    ]
  },
  {
    "symbol": "IVZ",
    "name": "INVESCO LTD",
    "sector": "finance",
    "aliases": [
      "IVZ",
      "INVESCO LTD"
    ]
  },
  {
    "symbol": "INVH",
    "name": "Invitation Homes",
    "sector": "realestate",
    "aliases": [
      "INVH",
      "Invitation Homes"
    ]
  },
  {
    "symbol": "IQV",
    "name": "IQVIA HOLDINGS INC",
    "sector": "healthcare",
    "aliases": [
      "IQV",
      "IQVIA INC",
      "IQVIA HOLDINGS INC"
    ]
  },
  {
    "symbol": "IRM",
    "name": "Iron Mountain",
    "sector": "realestate",
    "aliases": [
      "IRM",
      "Iron Mountain"
    ]
  },
  {
    "symbol": "JBHT",
    "name": "HUNT (JB) TRANSPRT SVCS INC",
    "sector": "industrials",
    "aliases": [
      "JBHT",
      "HUNT (JB) TRANSPRT SVCS INC"
    ]
  },
  {
    "symbol": "JBL",
    "name": "JABIL INC",
    "sector": "tech",
    "aliases": [
      "JBL",
      "JABIL INC"
    ]
  },
  {
    "symbol": "JKHY",
    "name": "JACK HENRY & ASSOCIATES INC",
    "sector": "finance",
    "aliases": [
      "JKHY",
      "JACK HENRY & ASSOCIATES INC"
    ]
  },
  {
    "symbol": "J",
    "name": "JACOBS SOLUTIONS INC",
    "sector": "industrials",
    "aliases": [
      "J",
      "JACOBS SOLUTIONS INC"
    ]
  },
  {
    "symbol": "JNJ",
    "name": "JOHNSON & JOHNSON",
    "sector": "healthcare",
    "aliases": [
      "JNJ",
      "JOHNSON & JOHNSON"
    ]
  },
  {
    "symbol": "JCI",
    "name": "JOHNSON CONTROLS INTERNATION",
    "sector": "industrials",
    "aliases": [
      "JCI",
      "JOHNSON CONTROLS INTERNATION"
    ]
  },
  {
    "symbol": "JPM",
    "name": "JPMORGAN CHASE & CO",
    "sector": "finance",
    "aliases": [
      "JPM",
      "JPMORGAN CHASE & CO"
    ]
  },
  {
    "symbol": "KVUE",
    "name": "KENVUE INC",
    "sector": "consumer",
    "aliases": [
      "KVUE",
      "KENVUE INC"
    ]
  },
  {
    "symbol": "KDP",
    "name": "KEURIG DR PEPPER INC",
    "sector": "consumer",
    "aliases": [
      "KDP",
      "KEURIG DR PEPPER INC"
    ]
  },
  {
    "symbol": "KEY",
    "name": "KEYCORP",
    "sector": "finance",
    "aliases": [
      "KEY",
      "KEYCORP"
    ]
  },
  {
    "symbol": "KEYS",
    "name": "KEYSIGHT TECHNOLOGIES IN",
    "sector": "tech",
    "aliases": [
      "KEYS",
      "KEYSIGHT TECHNOLOGIES IN"
    ]
  },
  {
    "symbol": "KMB",
    "name": "KIMBERLY-CLARK CORP",
    "sector": "consumer",
    "aliases": [
      "KMB",
      "KIMBERLY-CLARK CORP"
    ]
  },
  {
    "symbol": "KIM",
    "name": "Kimco Realty",
    "sector": "realestate",
    "aliases": [
      "KIM",
      "Kimco Realty"
    ]
  },
  {
    "symbol": "KMI",
    "name": "KINDER MORGAN INC",
    "sector": "energy",
    "aliases": [
      "KMI",
      "KINDER MORGAN INC"
    ]
  },
  {
    "symbol": "KKR",
    "name": "KKR & CO INC",
    "sector": "finance",
    "aliases": [
      "KKR",
      "KKR & CO INC"
    ]
  },
  {
    "symbol": "KLAC",
    "name": "KLA CORP",
    "sector": "tech",
    "aliases": [
      "KLAC",
      "KLA CORP"
    ]
  },
  {
    "symbol": "KHC",
    "name": "KRAFT HEINZ CO/THE",
    "sector": "consumer",
    "aliases": [
      "KHC",
      "KRAFT HEINZ CO/THE"
    ]
  },
  {
    "symbol": "KR",
    "name": "KROGER CO",
    "sector": "consumer",
    "aliases": [
      "KR",
      "KROGER CO"
    ]
  },
  {
    "symbol": "LHX",
    "name": "L3HARRIS TECHNOLOGIES INC",
    "sector": "industrials",
    "aliases": [
      "LHX",
      "L3HARRIS TECHNOLOGIES INC"
    ]
  },
  {
    "symbol": "LH",
    "name": "LABCORP HOLDINGS INC",
    "sector": "healthcare",
    "aliases": [
      "LH",
      "LABCORP INC",
      "LABCORP HOLDINGS INC"
    ]
  },
  {
    "symbol": "LRCX",
    "name": "LAM RESEARCH CORP",
    "sector": "tech",
    "aliases": [
      "LRCX",
      "LAM RESEARCH CORP"
    ]
  },
  {
    "symbol": "LVS",
    "name": "LAS VEGAS SANDS CORP",
    "sector": "consumer",
    "aliases": [
      "LVS",
      "LAS VEGAS SANDS CORP"
    ]
  },
  {
    "symbol": "LDOS",
    "name": "LEIDOS HOLDINGS INC",
    "sector": "industrials",
    "aliases": [
      "LDOS",
      "LEIDOS INC",
      "LEIDOS HOLDINGS INC"
    ]
  },
  {
    "symbol": "LEN",
    "name": "LENNAR CORP-A",
    "sector": "consumer",
    "aliases": [
      "LEN",
      "LENNAR CORP-A"
    ]
  },
  {
    "symbol": "LII",
    "name": "LENNOX INTERNATIONAL INC",
    "sector": "industrials",
    "aliases": [
      "LII",
      "LENNOX INTERNATIONAL INC"
    ]
  },
  {
    "symbol": "LLY",
    "name": "ELI LILLY & CO",
    "sector": "healthcare",
    "aliases": [
      "LLY",
      "ELI LILLY & CO"
    ]
  },
  {
    "symbol": "LIN",
    "name": "LINDE PLC",
    "sector": "materials",
    "aliases": [
      "LIN",
      "LINDE",
      "LINDE PLC"
    ]
  },
  {
    "symbol": "LYV",
    "name": "LIVE NATION ENTERTAINMENT IN",
    "sector": "telecom",
    "aliases": [
      "LYV",
      "LIVE NATION ENTERTAINMENT IN"
    ]
  },
  {
    "symbol": "LMT",
    "name": "LOCKHEED MARTIN CORP",
    "sector": "industrials",
    "aliases": [
      "LMT",
      "LOCKHEED MARTIN CORP"
    ]
  },
  {
    "symbol": "L",
    "name": "LOEWS CORP",
    "sector": "finance",
    "aliases": [
      "L",
      "LOEWS CORP"
    ]
  },
  {
    "symbol": "LOW",
    "name": "LOWE'S COS INC",
    "sector": "consumer",
    "aliases": [
      "LOW",
      "LOWE'S COS INC"
    ]
  },
  {
    "symbol": "LULU",
    "name": "LULULEMON ATHLETICA INC",
    "sector": "consumer",
    "aliases": [
      "LULU",
      "LULULEMON ATHLETICA INC"
    ]
  },
  {
    "symbol": "LITE",
    "name": "LUMENTUM HOLDINGS INC",
    "sector": "tech",
    "aliases": [
      "LITE",
      "LUMENTUM INC",
      "LUMENTUM HOLDINGS INC"
    ]
  },
  {
    "symbol": "LYB",
    "name": "LYONDELLBASELL INDU-CL A",
    "sector": "materials",
    "aliases": [
      "LYB",
      "LYONDELLBASELL INDU-CL A"
    ]
  },
  {
    "symbol": "MTB",
    "name": "M & T BANK CORP",
    "sector": "finance",
    "aliases": [
      "MTB",
      "M & T BANK CORP"
    ]
  },
  {
    "symbol": "MPC",
    "name": "MARATHON PETROLEUM CORP",
    "sector": "energy",
    "aliases": [
      "MPC",
      "MARATHON PETROLEUM CORP"
    ]
  },
  {
    "symbol": "MAR",
    "name": "MARRIOTT INTERNATIONAL -CL A",
    "sector": "consumer",
    "aliases": [
      "MAR",
      "MARRIOTT INTERNATIONAL -CL A"
    ]
  },
  {
    "symbol": "MRSH",
    "name": "MARSH & MCLENNAN COS",
    "sector": "finance",
    "aliases": [
      "MRSH",
      "MARSH & MCLENNAN COS"
    ]
  },
  {
    "symbol": "MLM",
    "name": "MARTIN MARIETTA MATERIALS",
    "sector": "materials",
    "aliases": [
      "MLM",
      "MARTIN MARIETTA MATERIALS"
    ]
  },
  {
    "symbol": "MRVL",
    "name": "MARVELL TECHNOLOGY INC",
    "sector": "tech",
    "aliases": [
      "MRVL",
      "MARVELL TECHNOLOGY INC"
    ]
  },
  {
    "symbol": "MAS",
    "name": "MASCO CORP",
    "sector": "industrials",
    "aliases": [
      "MAS",
      "MASCO CORP"
    ]
  },
  {
    "symbol": "MA",
    "name": "MASTERCARD INC - A",
    "sector": "finance",
    "aliases": [
      "MA",
      "MASTERCARD INC - A"
    ]
  },
  {
    "symbol": "MKC",
    "name": "MCCORMICK & CO-NON VTG SHRS",
    "sector": "consumer",
    "aliases": [
      "MKC",
      "MCCORMICK & CO-NON VTG SHRS"
    ]
  },
  {
    "symbol": "MCD",
    "name": "MCDONALD'S CORP",
    "sector": "consumer",
    "aliases": [
      "MCD",
      "MCDONALD'S CORP"
    ]
  },
  {
    "symbol": "MCK",
    "name": "MCKESSON CORP",
    "sector": "healthcare",
    "aliases": [
      "MCK",
      "MCKESSON CORP"
    ]
  },
  {
    "symbol": "MDT",
    "name": "MEDTRONIC PLC",
    "sector": "healthcare",
    "aliases": [
      "MDT",
      "MEDTRONIC",
      "MEDTRONIC PLC"
    ]
  },
  {
    "symbol": "MRK",
    "name": "MERCK & CO. INC.",
    "sector": "healthcare",
    "aliases": [
      "MRK",
      "MERCK & CO. INC."
    ]
  },
  {
    "symbol": "META",
    "name": "META PLATFORMS INC-CLASS A",
    "sector": "telecom",
    "aliases": [
      "META",
      "META PLATFORMS INC-CLASS A"
    ]
  },
  {
    "symbol": "MET",
    "name": "METLIFE INC",
    "sector": "finance",
    "aliases": [
      "MET",
      "METLIFE INC"
    ]
  },
  {
    "symbol": "MTD",
    "name": "METTLER-TOLEDO INTERNATIONAL",
    "sector": "healthcare",
    "aliases": [
      "MTD",
      "METTLER-TOLEDO INTERNATIONAL"
    ]
  },
  {
    "symbol": "MGM",
    "name": "MGM RESORTS INTERNATIONAL",
    "sector": "consumer",
    "aliases": [
      "MGM",
      "MGM RESORTS INTERNATIONAL"
    ]
  },
  {
    "symbol": "MCHP",
    "name": "MICROCHIP TECHNOLOGY INC",
    "sector": "tech",
    "aliases": [
      "MCHP",
      "MICROCHIP TECHNOLOGY INC"
    ]
  },
  {
    "symbol": "MU",
    "name": "MICRON TECHNOLOGY INC",
    "sector": "tech",
    "aliases": [
      "MU",
      "MICRON TECHNOLOGY INC"
    ]
  },
  {
    "symbol": "MSFT",
    "name": "MICROSOFT CORP",
    "sector": "tech",
    "aliases": [
      "MSFT",
      "MICROSOFT CORP"
    ]
  },
  {
    "symbol": "MAA",
    "name": "Mid-America Apartment Communities",
    "sector": "realestate",
    "aliases": [
      "MAA",
      "Mid-America Apartment Communities"
    ]
  },
  {
    "symbol": "MRNA",
    "name": "MODERNA INC",
    "sector": "healthcare",
    "aliases": [
      "MRNA",
      "MODERNA INC"
    ]
  },
  {
    "symbol": "TAP",
    "name": "MOLSON COORS BEVERAGE CO - B",
    "sector": "consumer",
    "aliases": [
      "TAP",
      "MOLSON COORS BEVERAGE CO - B"
    ]
  },
  {
    "symbol": "MDLZ",
    "name": "MONDELEZ INTERNATIONAL INC-A",
    "sector": "consumer",
    "aliases": [
      "MDLZ",
      "MONDELEZ INTERNATIONAL INC-A"
    ]
  },
  {
    "symbol": "MPWR",
    "name": "MONOLITHIC POWER SYSTEMS INC",
    "sector": "tech",
    "aliases": [
      "MPWR",
      "MONOLITHIC POWER SYSTEMS INC"
    ]
  },
  {
    "symbol": "MNST",
    "name": "MONSTER BEVERAGE CORP",
    "sector": "consumer",
    "aliases": [
      "MNST",
      "MONSTER BEVERAGE CORP"
    ]
  },
  {
    "symbol": "MCO",
    "name": "MOODY'S CORP",
    "sector": "finance",
    "aliases": [
      "MCO",
      "MOODY'S CORP"
    ]
  },
  {
    "symbol": "MS",
    "name": "MORGAN STANLEY",
    "sector": "finance",
    "aliases": [
      "MS",
      "MORGAN STANLEY"
    ]
  },
  {
    "symbol": "MOS",
    "name": "MOSAIC CO/THE",
    "sector": "materials",
    "aliases": [
      "MOS",
      "MOSAIC CO/THE"
    ]
  },
  {
    "symbol": "MSI",
    "name": "MOTOROLA SOLUTIONS INC",
    "sector": "tech",
    "aliases": [
      "MSI",
      "MOTOROLA SOLUTIONS INC"
    ]
  },
  {
    "symbol": "MSCI",
    "name": "MSCI INC",
    "sector": "finance",
    "aliases": [
      "MSCI",
      "MSCI INC"
    ]
  },
  {
    "symbol": "NDAQ",
    "name": "NASDAQ INC",
    "sector": "tech",
    "aliases": [
      "NDAQ",
      "NASDAQ INC"
    ]
  },
  {
    "symbol": "NTAP",
    "name": "NETAPP INC",
    "sector": "tech",
    "aliases": [
      "NTAP",
      "NETAPP INC"
    ]
  },
  {
    "symbol": "NFLX",
    "name": "NETFLIX INC",
    "sector": "telecom",
    "aliases": [
      "NFLX",
      "NETFLIX INC"
    ]
  },
  {
    "symbol": "NEM",
    "name": "NEWMONT CORP",
    "sector": "materials",
    "aliases": [
      "NEM",
      "NEWMONT CORP"
    ]
  },
  {
    "symbol": "NWSA",
    "name": "NEWS CORP - CLASS A",
    "sector": "telecom",
    "aliases": [
      "NWSA",
      "NEWS CORP - CLASS A"
    ]
  },
  {
    "symbol": "NWS",
    "name": "NEWS CORP - CLASS B",
    "sector": "telecom",
    "aliases": [
      "NWS",
      "NEWS CORP - CLASS B"
    ]
  },
  {
    "symbol": "NEE",
    "name": "NEXTERA ENERGY INC",
    "sector": "utilities",
    "aliases": [
      "NEE",
      "NEXTERA ENERGY INC"
    ]
  },
  {
    "symbol": "NKE",
    "name": "NIKE INC -CL B",
    "sector": "tech",
    "aliases": [
      "NKE",
      "NIKE INC -CL B"
    ]
  },
  {
    "symbol": "NI",
    "name": "NISOURCE INC",
    "sector": "utilities",
    "aliases": [
      "NI",
      "NISOURCE INC"
    ]
  },
  {
    "symbol": "NDSN",
    "name": "NORDSON CORP",
    "sector": "industrials",
    "aliases": [
      "NDSN",
      "NORDSON CORP"
    ]
  },
  {
    "symbol": "NSC",
    "name": "NORFOLK SOUTHERN CORP",
    "sector": "industrials",
    "aliases": [
      "NSC",
      "NORFOLK SOUTHERN CORP"
    ]
  },
  {
    "symbol": "NTRS",
    "name": "NORTHERN TRUST CORP",
    "sector": "finance",
    "aliases": [
      "NTRS",
      "NORTHERN TRUST CORP"
    ]
  },
  {
    "symbol": "NOC",
    "name": "NORTHROP GRUMMAN CORP",
    "sector": "industrials",
    "aliases": [
      "NOC",
      "NORTHROP GRUMMAN CORP"
    ]
  },
  {
    "symbol": "NCLH",
    "name": "NORWEGIAN CRUISE LINE HOLDIN",
    "sector": "consumer",
    "aliases": [
      "NCLH",
      "NORWEGIAN CRUISE LINE HOLDIN"
    ]
  },
  {
    "symbol": "NRG",
    "name": "NRG ENERGY INC",
    "sector": "utilities",
    "aliases": [
      "NRG",
      "NRG ENERGY INC"
    ]
  },
  {
    "symbol": "NUE",
    "name": "NUCOR CORP",
    "sector": "materials",
    "aliases": [
      "NUE",
      "NUCOR CORP"
    ]
  },
  {
    "symbol": "NVDA",
    "name": "NVIDIA CORP",
    "sector": "tech",
    "aliases": [
      "NVDA",
      "NVIDIA CORP"
    ]
  },
  {
    "symbol": "NVR",
    "name": "NVR INC",
    "sector": "tech",
    "aliases": [
      "NVR",
      "NVR INC"
    ]
  },
  {
    "symbol": "NXPI",
    "name": "NXP SEMICONDUCTORS NV",
    "sector": "tech",
    "aliases": [
      "NXPI",
      "NXP SEMICONDUCTORS NV"
    ]
  },
  {
    "symbol": "ORLY",
    "name": "O'REILLY AUTOMOTIVE INC",
    "sector": "consumer",
    "aliases": [
      "ORLY",
      "O'REILLY AUTOMOTIVE INC"
    ]
  },
  {
    "symbol": "OXY",
    "name": "OCCIDENTAL PETROLEUM CORP",
    "sector": "energy",
    "aliases": [
      "OXY",
      "OCCIDENTAL PETROLEUM CORP"
    ]
  },
  {
    "symbol": "ODFL",
    "name": "OLD DOMINION FREIGHT LINE",
    "sector": "industrials",
    "aliases": [
      "ODFL",
      "OLD DOMINION FREIGHT LINE"
    ]
  },
  {
    "symbol": "OMC",
    "name": "OMNICOM GROUP",
    "sector": "telecom",
    "aliases": [
      "OMC",
      "OMNICOM",
      "OMNICOM GROUP"
    ]
  },
  {
    "symbol": "ON",
    "name": "ON SEMICONDUCTOR",
    "sector": "tech",
    "aliases": [
      "ON",
      "ON SEMICONDUCTOR"
    ]
  },
  {
    "symbol": "OKE",
    "name": "ONEOK INC",
    "sector": "energy",
    "aliases": [
      "OKE",
      "ONEOK INC"
    ]
  },
  {
    "symbol": "ORCL",
    "name": "ORACLE CORP",
    "sector": "tech",
    "aliases": [
      "ORCL",
      "ORACLE CORP"
    ]
  },
  {
    "symbol": "OTIS",
    "name": "OTIS WORLDWIDE CORP",
    "sector": "industrials",
    "aliases": [
      "OTIS",
      "OTIS WORLDWIDE CORP"
    ]
  },
  {
    "symbol": "PCAR",
    "name": "PACCAR INC",
    "sector": "industrials",
    "aliases": [
      "PCAR",
      "PACCAR INC"
    ]
  },
  {
    "symbol": "PKG",
    "name": "PACKAGING CORP OF AMERICA",
    "sector": "materials",
    "aliases": [
      "PKG",
      "PACKAGING CORP OF AMERICA"
    ]
  },
  {
    "symbol": "PLTR",
    "name": "PALANTIR TECHNOLOGIES INC-A",
    "sector": "tech",
    "aliases": [
      "PLTR",
      "PALANTIR TECHNOLOGIES INC-A"
    ]
  },
  {
    "symbol": "PANW",
    "name": "PALO ALTO NETWORKS INC",
    "sector": "tech",
    "aliases": [
      "PANW",
      "PALO ALTO NETWORKS INC"
    ]
  },
  {
    "symbol": "PSKY",
    "name": "PARAMOUNT SKYDANCE CL B",
    "sector": "telecom",
    "aliases": [
      "PSKY",
      "PARAMOUNT SKYDANCE CL B"
    ]
  },
  {
    "symbol": "PH",
    "name": "PARKER HANNIFIN CORP",
    "sector": "industrials",
    "aliases": [
      "PH",
      "PARKER HANNIFIN CORP"
    ]
  },
  {
    "symbol": "PAYX",
    "name": "PAYCHEX INC",
    "sector": "industrials",
    "aliases": [
      "PAYX",
      "PAYCHEX INC"
    ]
  },
  {
    "symbol": "PYPL",
    "name": "PAYPAL HOLDINGS INC",
    "sector": "finance",
    "aliases": [
      "PYPL",
      "PAYPAL INC",
      "PAYPAL HOLDINGS INC"
    ]
  },
  {
    "symbol": "PNR",
    "name": "PENTAIR PLC",
    "sector": "industrials",
    "aliases": [
      "PNR",
      "PENTAIR",
      "PENTAIR PLC"
    ]
  },
  {
    "symbol": "PEP",
    "name": "PEPSICO INC",
    "sector": "consumer",
    "aliases": [
      "PEP",
      "PEPSICO INC"
    ]
  },
  {
    "symbol": "PFE",
    "name": "PFIZER INC",
    "sector": "healthcare",
    "aliases": [
      "PFE",
      "PFIZER INC"
    ]
  },
  {
    "symbol": "PCG",
    "name": "P G & E CORP",
    "sector": "utilities",
    "aliases": [
      "PCG",
      "P G & E CORP"
    ]
  },
  {
    "symbol": "PM",
    "name": "PHILIP MORRIS INTERNATIONAL",
    "sector": "consumer",
    "aliases": [
      "PM",
      "PHILIP MORRIS INTERNATIONAL"
    ]
  },
  {
    "symbol": "PSX",
    "name": "PHILLIPS 66",
    "sector": "energy",
    "aliases": [
      "PSX",
      "PHILLIPS 66"
    ]
  },
  {
    "symbol": "PNW",
    "name": "PINNACLE WEST CAPITAL",
    "sector": "utilities",
    "aliases": [
      "PNW",
      "PINNACLE WEST CAPITAL"
    ]
  },
  {
    "symbol": "PNC",
    "name": "PNC FINANCIAL SERVICES GROUP",
    "sector": "finance",
    "aliases": [
      "PNC",
      "PNC FINANCIAL SERVICES",
      "PNC FINANCIAL SERVICES GROUP"
    ]
  },
  {
    "symbol": "PPG",
    "name": "PPG INDUSTRIES INC",
    "sector": "materials",
    "aliases": [
      "PPG",
      "PPG INDUSTRIES INC"
    ]
  },
  {
    "symbol": "PPL",
    "name": "PPL CORP",
    "sector": "utilities",
    "aliases": [
      "PPL",
      "PPL CORP"
    ]
  },
  {
    "symbol": "PFG",
    "name": "PRINCIPAL FINANCIAL GROUP",
    "sector": "finance",
    "aliases": [
      "PFG",
      "PRINCIPAL FINANCIAL",
      "PRINCIPAL FINANCIAL GROUP"
    ]
  },
  {
    "symbol": "PG",
    "name": "PROCTER & GAMBLE CO/THE",
    "sector": "consumer",
    "aliases": [
      "PG",
      "PROCTER & GAMBLE CO/THE"
    ]
  },
  {
    "symbol": "PGR",
    "name": "PROGRESSIVE CORP",
    "sector": "finance",
    "aliases": [
      "PGR",
      "PROGRESSIVE CORP"
    ]
  },
  {
    "symbol": "PLD",
    "name": "Prologis",
    "sector": "realestate",
    "aliases": [
      "PLD",
      "Prologis"
    ]
  },
  {
    "symbol": "PRU",
    "name": "PRUDENTIAL FINANCIAL INC",
    "sector": "finance",
    "aliases": [
      "PRU",
      "PRUDENTIAL FINANCIAL INC"
    ]
  },
  {
    "symbol": "PEG",
    "name": "PUBLIC SERVICE ENTERPRISE GP",
    "sector": "utilities",
    "aliases": [
      "PEG",
      "PUBLIC SERVICE ENTERPRISE GP"
    ]
  },
  {
    "symbol": "PTC",
    "name": "PTC INC",
    "sector": "tech",
    "aliases": [
      "PTC",
      "PTC INC"
    ]
  },
  {
    "symbol": "PSA",
    "name": "Public Storage",
    "sector": "realestate",
    "aliases": [
      "PSA",
      "Public Storage"
    ]
  },
  {
    "symbol": "PHM",
    "name": "PULTEGROUP INC",
    "sector": "consumer",
    "aliases": [
      "PHM",
      "PULTEGROUP INC"
    ]
  },
  {
    "symbol": "PWR",
    "name": "QUANTA SERVICES INC",
    "sector": "industrials",
    "aliases": [
      "PWR",
      "QUANTA SERVICES INC"
    ]
  },
  {
    "symbol": "QCOM",
    "name": "QUALCOMM INC",
    "sector": "tech",
    "aliases": [
      "QCOM",
      "QUALCOMM INC"
    ]
  },
  {
    "symbol": "DGX",
    "name": "QUEST DIAGNOSTICS INC",
    "sector": "healthcare",
    "aliases": [
      "DGX",
      "QUEST DIAGNOSTICS INC"
    ]
  },
  {
    "symbol": "Q",
    "name": "QNITY ELECTRONICS INC",
    "sector": "tech",
    "aliases": [
      "Q",
      "QNITY ELECTRONICS INC"
    ]
  },
  {
    "symbol": "RL",
    "name": "RALPH LAUREN CORP",
    "sector": "consumer",
    "aliases": [
      "RL",
      "RALPH LAUREN CORP"
    ]
  },
  {
    "symbol": "RJF",
    "name": "RAYMOND JAMES FINANCIAL INC",
    "sector": "finance",
    "aliases": [
      "RJF",
      "RAYMOND JAMES FINANCIAL INC"
    ]
  },
  {
    "symbol": "RTX",
    "name": "RTX CORP",
    "sector": "industrials",
    "aliases": [
      "RTX",
      "RTX CORP"
    ]
  },
  {
    "symbol": "O",
    "name": "Realty Income",
    "sector": "realestate",
    "aliases": [
      "O",
      "Realty Income"
    ]
  },
  {
    "symbol": "REG",
    "name": "Regency Centers",
    "sector": "realestate",
    "aliases": [
      "REG",
      "Regency Centers"
    ]
  },
  {
    "symbol": "REGN",
    "name": "REGENERON PHARMACEUTICALS",
    "sector": "healthcare",
    "aliases": [
      "REGN",
      "REGENERON PHARMACEUTICALS"
    ]
  },
  {
    "symbol": "RF",
    "name": "REGIONS FINANCIAL CORP",
    "sector": "finance",
    "aliases": [
      "RF",
      "REGIONS FINANCIAL CORP"
    ]
  },
  {
    "symbol": "RSG",
    "name": "REPUBLIC SERVICES INC",
    "sector": "industrials",
    "aliases": [
      "RSG",
      "REPUBLIC SERVICES INC"
    ]
  },
  {
    "symbol": "RMD",
    "name": "RESMED INC",
    "sector": "healthcare",
    "aliases": [
      "RMD",
      "RESMED INC"
    ]
  },
  {
    "symbol": "RVTY",
    "name": "REVVITY INC",
    "sector": "healthcare",
    "aliases": [
      "RVTY",
      "REVVITY INC"
    ]
  },
  {
    "symbol": "HOOD",
    "name": "ROBINHOOD MARKETS INC - A",
    "sector": "finance",
    "aliases": [
      "HOOD",
      "ROBINHOOD MARKETS INC - A"
    ]
  },
  {
    "symbol": "ROK",
    "name": "ROCKWELL AUTOMATION INC",
    "sector": "industrials",
    "aliases": [
      "ROK",
      "ROCKWELL AUTOMATION INC"
    ]
  },
  {
    "symbol": "ROL",
    "name": "ROLLINS INC",
    "sector": "tech",
    "aliases": [
      "ROL",
      "ROLLINS INC"
    ]
  },
  {
    "symbol": "ROP",
    "name": "ROPER TECHNOLOGIES INC",
    "sector": "tech",
    "aliases": [
      "ROP",
      "ROPER TECHNOLOGIES INC"
    ]
  },
  {
    "symbol": "ROST",
    "name": "ROSS STORES INC",
    "sector": "consumer",
    "aliases": [
      "ROST",
      "ROSS STORES INC"
    ]
  },
  {
    "symbol": "RCL",
    "name": "ROYAL CARIBBEAN CRUISES LTD",
    "sector": "consumer",
    "aliases": [
      "RCL",
      "ROYAL CARIBBEAN CRUISES LTD"
    ]
  },
  {
    "symbol": "SPGI",
    "name": "S&P GLOBAL INC",
    "sector": "finance",
    "aliases": [
      "SPGI",
      "S&P GLOBAL INC"
    ]
  },
  {
    "symbol": "CRM",
    "name": "SALESFORCE INC",
    "sector": "tech",
    "aliases": [
      "CRM",
      "SALESFORCE INC"
    ]
  },
  {
    "symbol": "SNDK",
    "name": "SANDISK CORP",
    "sector": "tech",
    "aliases": [
      "SNDK",
      "SANDISK CORP"
    ]
  },
  {
    "symbol": "SBAC",
    "name": "SBA Communications",
    "sector": "realestate",
    "aliases": [
      "SBAC",
      "SBA Communications"
    ]
  },
  {
    "symbol": "SLB",
    "name": "SLB LTD",
    "sector": "energy",
    "aliases": [
      "SLB",
      "SLB LTD"
    ]
  },
  {
    "symbol": "STX",
    "name": "SEAGATE TECHNOLOGY HOLDINGS",
    "sector": "tech",
    "aliases": [
      "STX",
      "SEAGATE TECHNOLOGY",
      "SEAGATE TECHNOLOGY HOLDINGS"
    ]
  },
  {
    "symbol": "SRE",
    "name": "SEMPRA",
    "sector": "utilities",
    "aliases": [
      "SRE",
      "SEMPRA"
    ]
  },
  {
    "symbol": "NOW",
    "name": "SERVICENOW INC",
    "sector": "tech",
    "aliases": [
      "NOW",
      "SERVICENOW INC"
    ]
  },
  {
    "symbol": "SHW",
    "name": "SHERWIN-WILLIAMS CO/THE",
    "sector": "materials",
    "aliases": [
      "SHW",
      "SHERWIN-WILLIAMS CO/THE"
    ]
  },
  {
    "symbol": "SPG",
    "name": "Simon Property Group",
    "sector": "realestate",
    "aliases": [
      "SPG",
      "Simon Property",
      "Simon Property Group"
    ]
  },
  {
    "symbol": "SWKS",
    "name": "SKYWORKS SOLUTIONS INC",
    "sector": "tech",
    "aliases": [
      "SWKS",
      "SKYWORKS SOLUTIONS INC"
    ]
  },
  {
    "symbol": "SJM",
    "name": "JM SMUCKER CO/THE",
    "sector": "consumer",
    "aliases": [
      "SJM",
      "JM SMUCKER CO/THE"
    ]
  },
  {
    "symbol": "SW",
    "name": "SMURFIT WESTROCK PLC",
    "sector": "materials",
    "aliases": [
      "SW",
      "SMURFIT WESTROCK",
      "SMURFIT WESTROCK PLC"
    ]
  },
  {
    "symbol": "SNA",
    "name": "SNAP-ON INC",
    "sector": "industrials",
    "aliases": [
      "SNA",
      "SNAP-ON INC"
    ]
  },
  {
    "symbol": "SOLV",
    "name": "SOLVENTUM CORP",
    "sector": "healthcare",
    "aliases": [
      "SOLV",
      "SOLVENTUM CORP"
    ]
  },
  {
    "symbol": "SO",
    "name": "SOUTHERN CO/THE",
    "sector": "utilities",
    "aliases": [
      "SO",
      "SOUTHERN CO/THE"
    ]
  },
  {
    "symbol": "LUV",
    "name": "SOUTHWEST AIRLINES CO",
    "sector": "industrials",
    "aliases": [
      "LUV",
      "SOUTHWEST AIRLINES CO"
    ]
  },
  {
    "symbol": "SWK",
    "name": "STANLEY BLACK & DECKER INC",
    "sector": "industrials",
    "aliases": [
      "SWK",
      "STANLEY BLACK & DECKER INC"
    ]
  },
  {
    "symbol": "SBUX",
    "name": "STARBUCKS CORP",
    "sector": "consumer",
    "aliases": [
      "SBUX",
      "STARBUCKS CORP"
    ]
  },
  {
    "symbol": "STT",
    "name": "STATE STREET CORP",
    "sector": "finance",
    "aliases": [
      "STT",
      "STATE STREET CORP"
    ]
  },
  {
    "symbol": "STLD",
    "name": "STEEL DYNAMICS INC",
    "sector": "materials",
    "aliases": [
      "STLD",
      "STEEL DYNAMICS INC"
    ]
  },
  {
    "symbol": "STE",
    "name": "STERIS PLC",
    "sector": "healthcare",
    "aliases": [
      "STE",
      "STERIS",
      "STERIS PLC"
    ]
  },
  {
    "symbol": "SYK",
    "name": "STRYKER CORP",
    "sector": "healthcare",
    "aliases": [
      "SYK",
      "STRYKER CORP"
    ]
  },
  {
    "symbol": "SMCI",
    "name": "SUPER MICRO COMPUTER INC",
    "sector": "tech",
    "aliases": [
      "SMCI",
      "SUPER MICRO COMPUTER INC"
    ]
  },
  {
    "symbol": "SYF",
    "name": "SYNCHRONY FINANCIAL",
    "sector": "finance",
    "aliases": [
      "SYF",
      "SYNCHRONY FINANCIAL"
    ]
  },
  {
    "symbol": "SNPS",
    "name": "SYNOPSYS INC",
    "sector": "tech",
    "aliases": [
      "SNPS",
      "SYNOPSYS INC"
    ]
  },
  {
    "symbol": "SYY",
    "name": "SYSCO CORP",
    "sector": "consumer",
    "aliases": [
      "SYY",
      "SYSCO CORP"
    ]
  },
  {
    "symbol": "TMUS",
    "name": "T-MOBILE US INC",
    "sector": "telecom",
    "aliases": [
      "TMUS",
      "T-MOBILE US INC"
    ]
  },
  {
    "symbol": "TROW",
    "name": "T ROWE PRICE GROUP INC",
    "sector": "finance",
    "aliases": [
      "TROW",
      "T ROWE PRICE INC",
      "T ROWE PRICE GROUP INC"
    ]
  },
  {
    "symbol": "TTWO",
    "name": "TAKE-TWO INTERACTIVE SOFTWRE",
    "sector": "telecom",
    "aliases": [
      "TTWO",
      "TAKE-TWO INTERACTIVE SOFTWRE"
    ]
  },
  {
    "symbol": "TPR",
    "name": "TAPESTRY INC",
    "sector": "tech",
    "aliases": [
      "TPR",
      "TAPESTRY INC"
    ]
  },
  {
    "symbol": "TRGP",
    "name": "TARGA RESOURCES CORP",
    "sector": "energy",
    "aliases": [
      "TRGP",
      "TARGA RESOURCES CORP"
    ]
  },
  {
    "symbol": "TGT",
    "name": "TARGET CORP",
    "sector": "consumer",
    "aliases": [
      "TGT",
      "TARGET CORP"
    ]
  },
  {
    "symbol": "TEL",
    "name": "TE CONNECTIVITY PLC",
    "sector": "tech",
    "aliases": [
      "TEL",
      "TE CONNECTIVITY",
      "TE CONNECTIVITY PLC"
    ]
  },
  {
    "symbol": "TDY",
    "name": "TELEDYNE TECHNOLOGIES INC",
    "sector": "tech",
    "aliases": [
      "TDY",
      "TELEDYNE TECHNOLOGIES INC"
    ]
  },
  {
    "symbol": "TER",
    "name": "TERADYNE INC",
    "sector": "tech",
    "aliases": [
      "TER",
      "TERADYNE INC"
    ]
  },
  {
    "symbol": "TSLA",
    "name": "TESLA INC",
    "sector": "tech",
    "aliases": [
      "TSLA",
      "TESLA INC"
    ]
  },
  {
    "symbol": "TXN",
    "name": "TEXAS INSTRUMENTS INC",
    "sector": "tech",
    "aliases": [
      "TXN",
      "TEXAS INSTRUMENTS INC"
    ]
  },
  {
    "symbol": "TPL",
    "name": "TEXAS PACIFIC LAND CORP",
    "sector": "energy",
    "aliases": [
      "TPL",
      "TEXAS PACIFIC LAND CORP"
    ]
  },
  {
    "symbol": "TXT",
    "name": "TEXTRON INC",
    "sector": "industrials",
    "aliases": [
      "TXT",
      "TEXTRON INC"
    ]
  },
  {
    "symbol": "TMO",
    "name": "THERMO FISHER SCIENTIFIC INC",
    "sector": "healthcare",
    "aliases": [
      "TMO",
      "THERMO FISHER SCIENTIFIC INC"
    ]
  },
  {
    "symbol": "TJX",
    "name": "TJX COMPANIES INC",
    "sector": "consumer",
    "aliases": [
      "TJX",
      "TJX COMPANIES INC"
    ]
  },
  {
    "symbol": "TKO",
    "name": "TKO GROUP HOLDINGS INC",
    "sector": "telecom",
    "aliases": [
      "TKO",
      "TKO INC",
      "TKO GROUP HOLDINGS INC"
    ]
  },
  {
    "symbol": "TTD",
    "name": "TRADE DESK INC/THE -CLASS A",
    "sector": "telecom",
    "aliases": [
      "TTD",
      "TRADE DESK INC/THE -CLASS A"
    ]
  },
  {
    "symbol": "TSCO",
    "name": "TRACTOR SUPPLY COMPANY",
    "sector": "consumer",
    "aliases": [
      "TSCO",
      "TRACTOR SUPPLY",
      "TRACTOR SUPPLY COMPANY"
    ]
  },
  {
    "symbol": "TT",
    "name": "TRANE TECHNOLOGIES PLC",
    "sector": "industrials",
    "aliases": [
      "TT",
      "TRANE TECHNOLOGIES",
      "TRANE TECHNOLOGIES PLC"
    ]
  },
  {
    "symbol": "TDG",
    "name": "TRANSDIGM GROUP INC",
    "sector": "industrials",
    "aliases": [
      "TDG",
      "TRANSDIGM INC",
      "TRANSDIGM GROUP INC"
    ]
  },
  {
    "symbol": "TRV",
    "name": "TRAVELERS COS INC/THE",
    "sector": "finance",
    "aliases": [
      "TRV",
      "TRAVELERS COS INC/THE"
    ]
  },
  {
    "symbol": "TRMB",
    "name": "TRIMBLE INC",
    "sector": "tech",
    "aliases": [
      "TRMB",
      "TRIMBLE INC"
    ]
  },
  {
    "symbol": "TFC",
    "name": "TRUIST FINANCIAL CORP",
    "sector": "finance",
    "aliases": [
      "TFC",
      "TRUIST FINANCIAL CORP"
    ]
  },
  {
    "symbol": "TYL",
    "name": "TYLER TECHNOLOGIES INC",
    "sector": "tech",
    "aliases": [
      "TYL",
      "TYLER TECHNOLOGIES INC"
    ]
  },
  {
    "symbol": "TSN",
    "name": "TYSON FOODS INC-CL A",
    "sector": "consumer",
    "aliases": [
      "TSN",
      "TYSON FOODS INC-CL A"
    ]
  },
  {
    "symbol": "USB",
    "name": "US BANCORP",
    "sector": "finance",
    "aliases": [
      "USB",
      "US BANCORP"
    ]
  },
  {
    "symbol": "UBER",
    "name": "UBER TECHNOLOGIES INC",
    "sector": "industrials",
    "aliases": [
      "UBER",
      "UBER TECHNOLOGIES INC"
    ]
  },
  {
    "symbol": "UDR",
    "name": "UDR",
    "sector": "tech",
    "aliases": [
      "UDR"
    ]
  },
  {
    "symbol": "ULTA",
    "name": "ULTA BEAUTY INC",
    "sector": "consumer",
    "aliases": [
      "ULTA",
      "ULTA BEAUTY INC"
    ]
  },
  {
    "symbol": "UNP",
    "name": "UNION PACIFIC CORP",
    "sector": "industrials",
    "aliases": [
      "UNP",
      "UNION PACIFIC CORP"
    ]
  },
  {
    "symbol": "UAL",
    "name": "UNITED AIRLINES HOLDINGS INC",
    "sector": "industrials",
    "aliases": [
      "UAL",
      "UNITED AIRLINES INC",
      "UNITED AIRLINES HOLDINGS INC"
    ]
  },
  {
    "symbol": "UPS",
    "name": "UNITED PARCEL SERVICE-CL B",
    "sector": "industrials",
    "aliases": [
      "UPS",
      "UNITED PARCEL SERVICE-CL B"
    ]
  },
  {
    "symbol": "URI",
    "name": "UNITED RENTALS INC",
    "sector": "industrials",
    "aliases": [
      "URI",
      "UNITED RENTALS INC"
    ]
  },
  {
    "symbol": "UNH",
    "name": "UNITEDHEALTH GROUP INC",
    "sector": "healthcare",
    "aliases": [
      "UNH",
      "UNITEDHEALTH INC",
      "UNITEDHEALTH GROUP INC"
    ]
  },
  {
    "symbol": "UHS",
    "name": "UNIVERSAL HEALTH SERVICES-B",
    "sector": "healthcare",
    "aliases": [
      "UHS",
      "UNIVERSAL HEALTH SERVICES-B"
    ]
  },
  {
    "symbol": "VLO",
    "name": "VALERO ENERGY CORP",
    "sector": "energy",
    "aliases": [
      "VLO",
      "VALERO ENERGY CORP"
    ]
  },
  {
    "symbol": "VEEV",
    "name": "VEEVA SYSTEMS INC-CLASS A",
    "sector": "healthcare",
    "aliases": [
      "VEEV",
      "VEEVA SYSTEMS INC-CLASS A"
    ]
  },
  {
    "symbol": "VTR",
    "name": "Ventas",
    "sector": "realestate",
    "aliases": [
      "VTR",
      "Ventas"
    ]
  },
  {
    "symbol": "VLTO",
    "name": "VERALTO CORP",
    "sector": "industrials",
    "aliases": [
      "VLTO",
      "VERALTO CORP"
    ]
  },
  {
    "symbol": "VRSN",
    "name": "VERISIGN INC",
    "sector": "tech",
    "aliases": [
      "VRSN",
      "VERISIGN INC"
    ]
  },
  {
    "symbol": "VRSK",
    "name": "VERISK ANALYTICS INC",
    "sector": "industrials",
    "aliases": [
      "VRSK",
      "VERISK ANALYTICS INC"
    ]
  },
  {
    "symbol": "VZ",
    "name": "VERIZON COMMUNICATIONS INC",
    "sector": "telecom",
    "aliases": [
      "VZ",
      "VERIZON COMMUNICATIONS INC"
    ]
  },
  {
    "symbol": "VRTX",
    "name": "VERTEX PHARMACEUTICALS INC",
    "sector": "healthcare",
    "aliases": [
      "VRTX",
      "VERTEX PHARMACEUTICALS INC"
    ]
  },
  {
    "symbol": "VRT",
    "name": "VERTIV HOLDINGS CO-A",
    "sector": "industrials",
    "aliases": [
      "VRT",
      "VERTIV CO-A",
      "VERTIV HOLDINGS CO-A"
    ]
  },
  {
    "symbol": "VTRS",
    "name": "VIATRIS INC",
    "sector": "healthcare",
    "aliases": [
      "VTRS",
      "VIATRIS INC"
    ]
  },
  {
    "symbol": "VICI",
    "name": "Vici Properties",
    "sector": "realestate",
    "aliases": [
      "VICI",
      "Vici Properties"
    ]
  },
  {
    "symbol": "V",
    "name": "VISA INC-CLASS A SHARES",
    "sector": "finance",
    "aliases": [
      "V",
      "VISA INC-CLASS A SHARES"
    ]
  },
  {
    "symbol": "VST",
    "name": "VISTRA CORP",
    "sector": "utilities",
    "aliases": [
      "VST",
      "VISTRA CORP"
    ]
  },
  {
    "symbol": "VMC",
    "name": "VULCAN MATERIALS CO",
    "sector": "materials",
    "aliases": [
      "VMC",
      "VULCAN MATERIALS CO"
    ]
  },
  {
    "symbol": "WRB",
    "name": "WR BERKLEY CORP",
    "sector": "finance",
    "aliases": [
      "WRB",
      "WR BERKLEY CORP"
    ]
  },
  {
    "symbol": "GWW",
    "name": "WW GRAINGER INC",
    "sector": "industrials",
    "aliases": [
      "GWW",
      "WW GRAINGER INC"
    ]
  },
  {
    "symbol": "WAB",
    "name": "WABTEC CORP",
    "sector": "industrials",
    "aliases": [
      "WAB",
      "WABTEC CORP"
    ]
  },
  {
    "symbol": "WMT",
    "name": "WALMART INC",
    "sector": "consumer",
    "aliases": [
      "WMT",
      "WALMART INC"
    ]
  },
  {
    "symbol": "DIS",
    "name": "WALT DISNEY CO/THE",
    "sector": "telecom",
    "aliases": [
      "DIS",
      "WALT DISNEY CO/THE"
    ]
  },
  {
    "symbol": "WBD",
    "name": "WARNER BROS DISCOVERY INC",
    "sector": "telecom",
    "aliases": [
      "WBD",
      "WARNER BROS DISCOVERY INC"
    ]
  },
  {
    "symbol": "WM",
    "name": "WASTE MANAGEMENT INC",
    "sector": "industrials",
    "aliases": [
      "WM",
      "WASTE MANAGEMENT INC"
    ]
  },
  {
    "symbol": "WAT",
    "name": "WATERS CORP",
    "sector": "healthcare",
    "aliases": [
      "WAT",
      "WATERS CORP"
    ]
  },
  {
    "symbol": "WEC",
    "name": "WEC ENERGY GROUP INC",
    "sector": "utilities",
    "aliases": [
      "WEC",
      "WEC ENERGY INC",
      "WEC ENERGY GROUP INC"
    ]
  },
  {
    "symbol": "WFC",
    "name": "WELLS FARGO & CO",
    "sector": "finance",
    "aliases": [
      "WFC",
      "WELLS FARGO & CO"
    ]
  },
  {
    "symbol": "WELL",
    "name": "Welltower",
    "sector": "realestate",
    "aliases": [
      "WELL",
      "Welltower"
    ]
  },
  {
    "symbol": "WST",
    "name": "WEST PHARMACEUTICAL SERVICES",
    "sector": "healthcare",
    "aliases": [
      "WST",
      "WEST PHARMACEUTICAL SERVICES"
    ]
  },
  {
    "symbol": "WDC",
    "name": "WESTERN DIGITAL CORP",
    "sector": "tech",
    "aliases": [
      "WDC",
      "WESTERN DIGITAL CORP"
    ]
  },
  {
    "symbol": "WY",
    "name": "Weyerhaeuser",
    "sector": "realestate",
    "aliases": [
      "WY",
      "Weyerhaeuser"
    ]
  },
  {
    "symbol": "WSM",
    "name": "WILLIAMS-SONOMA INC",
    "sector": "tech",
    "aliases": [
      "WSM",
      "WILLIAMS-SONOMA INC"
    ]
  },
  {
    "symbol": "WMB",
    "name": "WILLIAMS COS INC",
    "sector": "energy",
    "aliases": [
      "WMB",
      "WILLIAMS COS INC"
    ]
  },
  {
    "symbol": "WTW",
    "name": "WILLIS TOWERS WATSON PLC",
    "sector": "finance",
    "aliases": [
      "WTW",
      "WILLIS TOWERS WATSON",
      "WILLIS TOWERS WATSON PLC"
    ]
  },
  {
    "symbol": "WDAY",
    "name": "WORKDAY INC-CLASS A",
    "sector": "tech",
    "aliases": [
      "WDAY",
      "WORKDAY INC-CLASS A"
    ]
  },
  {
    "symbol": "WYNN",
    "name": "WYNN RESORTS LTD",
    "sector": "consumer",
    "aliases": [
      "WYNN",
      "WYNN RESORTS LTD"
    ]
  },
  {
    "symbol": "XEL",
    "name": "XCEL ENERGY INC",
    "sector": "utilities",
    "aliases": [
      "XEL",
      "XCEL ENERGY INC"
    ]
  },
  {
    "symbol": "XYL",
    "name": "XYLEM INC",
    "sector": "industrials",
    "aliases": [
      "XYL",
      "XYLEM INC"
    ]
  },
  {
    "symbol": "YUM",
    "name": "YUM! BRANDS INC",
    "sector": "consumer",
    "aliases": [
      "YUM",
      "YUM! BRANDS INC"
    ]
  },
  {
    "symbol": "ZBRA",
    "name": "ZEBRA TECHNOLOGIES CORP-CL A",
    "sector": "tech",
    "aliases": [
      "ZBRA",
      "ZEBRA TECHNOLOGIES CORP-CL A"
    ]
  },
  {
    "symbol": "ZBH",
    "name": "ZIMMER BIOMET HOLDINGS INC",
    "sector": "healthcare",
    "aliases": [
      "ZBH",
      "ZIMMER BIOMET INC",
      "ZIMMER BIOMET HOLDINGS INC"
    ]
  },
  {
    "symbol": "ZTS",
    "name": "ZOETIS INC",
    "sector": "healthcare",
    "aliases": [
      "ZTS",
      "ZOETIS INC"
    ]
  }
] as const

export const US_EQUITIES_SYMBOLS: readonly string[] = US_EQUITIES_TICKERS.map((t) => t.symbol)

export const US_EQUITIES_ALIASES: Record<string, readonly string[]> = Object.fromEntries(
  US_EQUITIES_TICKERS.map((t) => [t.symbol, t.aliases])
)
