import { readFile, writeFile, mkdir } from "fs/promises"
import { resolve } from "path"
import { TOP100_TICKERS_DATA } from "../lib/pipeline/sp500"

async function loadEnv() {
  try {
    const envPath = resolve(process.cwd(), ".env.local")
    const envText = await readFile(envPath, "utf8")
    for (const line of envText.split(/\r?\n/)) {
      const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/)
      if (match && !process.env[match[1]]) {
        process.env[match[1]] = match[2].replace(/^(['"])(.*)\1$/, "$2")
      }
    }
  } catch {
    // Fall back to process.env
  }
}

async function main() {
  await loadEnv()
  const apiKey = process.env.FINNHUB_API_KEY
  if (!apiKey) {
    throw new Error("Missing FINNHUB_API_KEY in environment")
  }

  console.log("[fetch-tickers] Calling Finnhub stock/symbol endpoint...")
  const res = await fetch(`https://finnhub.io/api/v1/stock/symbol?exchange=US&token=${apiKey}`)
  if (!res.ok) {
    throw new Error(`Finnhub API error ${res.status}: ${await res.text()}`)
  }

  const rawSymbols = (await res.json()) as Array<{
    symbol: string
    description: string
    type: string
    mic: string
  }>

  // Filter to US Common Stock on NYSE (XNYS) or NASDAQ (XNAS)
  const filteredFinnhub = rawSymbols.filter(
    (item) => item.type === "Common Stock" && (item.mic === "XNYS" || item.mic === "XNAS")
  )

  const finnhubMap = new Map<string, { description: string; mic: string }>(
    filteredFinnhub.map((item) => [item.symbol, { description: item.description, mic: item.mic }])
  )

  // Map constituents to official Finnhub metadata where available
  const tickers = TOP100_TICKERS_DATA.map((constituent) => {
    const finnhubItem = finnhubMap.get(constituent.symbol)
    return {
      symbol: constituent.symbol,
      name: finnhubItem?.description || constituent.name,
      sector: constituent.sector,
      aliases: constituent.aliases,
    }
  })

  console.log(`[fetch-tickers] Matched ${tickers.length} tickers from Finnhub API (out of ${rawSymbols.length} raw symbols).`)

  const fileContent = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
 * Generated by scripts/fetch-tickers.ts via Finnhub API.
 * Timestamp: ${new Date().toISOString()}
 */

export type EquityTicker = {
  symbol: string
  name: string
  sector: string
  aliases: readonly string[]
}

export const US_EQUITIES_TICKERS: readonly EquityTicker[] = ${JSON.stringify(tickers, null, 2)} as const

export const US_EQUITIES_SYMBOLS: readonly string[] = US_EQUITIES_TICKERS.map((t) => t.symbol)

export const US_EQUITIES_ALIASES: Record<string, readonly string[]> = Object.fromEntries(
  US_EQUITIES_TICKERS.map((t) => [t.symbol, t.aliases])
)
`

  const targetDir = resolve(process.cwd(), "lib/pipeline/markets")
  await mkdir(targetDir, { recursive: true })

  const targetFile = resolve(targetDir, "us-equities.ts")
  await writeFile(targetFile, fileContent, "utf8")
  console.log(`[fetch-tickers] Successfully wrote ${tickers.length} tickers to ${targetFile}`)
}

main().catch(console.error)
