-- Populate tickers table with full S&P 500 constituents universe
INSERT INTO tickers (symbol, name, sector, exchange, price, change_pct, direction)
VALUES
  ('MMM', '3M', 'macro', 'US', 0, 0, 'up'),
  ('AOS', 'A. O. Smith', 'macro', 'US', 0, 0, 'up'),
  ('ABT', 'Abbott Laboratories', 'macro', 'US', 0, 0, 'up'),
  ('ABBV', 'AbbVie', 'macro', 'US', 0, 0, 'up'),
  ('ACN', 'Accenture', 'tech', 'US', 0, 0, 'up'),
  ('ADBE', 'Adobe Inc.', 'tech', 'US', 0, 0, 'up'),
  ('AMD', 'Advanced Micro Devices', 'tech', 'US', 0, 0, 'up'),
  ('AES', 'AES Corporation', 'energy', 'US', 0, 0, 'up'),
  ('AFL', 'Aflac', 'finance', 'US', 0, 0, 'up'),
  ('A', 'Agilent Technologies', 'macro', 'US', 0, 0, 'up'),
  ('APD', 'Air Products', 'energy', 'US', 0, 0, 'up'),
  ('ABNB', 'Airbnb', 'macro', 'US', 0, 0, 'up'),
  ('AKAM', 'Akamai Technologies', 'tech', 'US', 0, 0, 'up'),
  ('ALB', 'Albemarle Corporation', 'energy', 'US', 0, 0, 'up'),
  ('ARE', 'Alexandria Real Estate Equities', 'finance', 'US', 0, 0, 'up'),
  ('ALGN', 'Align Technology', 'macro', 'US', 0, 0, 'up'),
  ('ALLE', 'Allegion', 'macro', 'US', 0, 0, 'up'),
  ('LNT', 'Alliant Energy', 'energy', 'US', 0, 0, 'up'),
  ('ALL', 'Allstate', 'finance', 'US', 0, 0, 'up'),
  ('GOOGL', 'Alphabet Inc. (Class A)', 'tech', 'US', 0, 0, 'up'),
  ('GOOG', 'Alphabet Inc. (Class C)', 'tech', 'US', 0, 0, 'up'),
  ('MO', 'Altria', 'macro', 'US', 0, 0, 'up'),
  ('AMZN', 'Amazon', 'macro', 'US', 0, 0, 'up'),
  ('AMCR', 'Amcor', 'energy', 'US', 0, 0, 'up'),
  ('AEE', 'Ameren', 'energy', 'US', 0, 0, 'up'),
  ('AEP', 'American Electric Power', 'energy', 'US', 0, 0, 'up'),
  ('AXP', 'American Express', 'finance', 'US', 0, 0, 'up'),
  ('AIG', 'American International Group', 'finance', 'US', 0, 0, 'up'),
  ('AMT', 'American Tower', 'finance', 'US', 0, 0, 'up'),
  ('AWK', 'American Water Works', 'energy', 'US', 0, 0, 'up'),
  ('AMP', 'Ameriprise Financial', 'finance', 'US', 0, 0, 'up'),
  ('AME', 'Ametek', 'macro', 'US', 0, 0, 'up'),
  ('AMGN', 'Amgen', 'macro', 'US', 0, 0, 'up'),
  ('APH', 'Amphenol', 'tech', 'US', 0, 0, 'up'),
  ('ADI', 'Analog Devices', 'tech', 'US', 0, 0, 'up'),
  ('AON', 'Aon plc', 'finance', 'US', 0, 0, 'up'),
  ('APA', 'APA Corporation', 'energy', 'US', 0, 0, 'up'),
  ('APO', 'Apollo Global Management', 'finance', 'US', 0, 0, 'up'),
  ('AAPL', 'Apple Inc.', 'tech', 'US', 0, 0, 'up'),
  ('AMAT', 'Applied Materials', 'tech', 'US', 0, 0, 'up'),
  ('APP', 'AppLovin', 'tech', 'US', 0, 0, 'up'),
  ('APTV', 'Aptiv', 'macro', 'US', 0, 0, 'up'),
  ('ACGL', 'Arch Capital Group', 'finance', 'US', 0, 0, 'up'),
  ('ADM', 'Archer Daniels Midland', 'macro', 'US', 0, 0, 'up'),
  ('ARES', 'Ares Management', 'finance', 'US', 0, 0, 'up'),
  ('ANET', 'Arista Networks', 'tech', 'US', 0, 0, 'up'),
  ('AJG', 'Arthur J. Gallagher & Co.', 'finance', 'US', 0, 0, 'up'),
  ('AIZ', 'Assurant', 'finance', 'US', 0, 0, 'up'),
  ('T', 'AT&T', 'tech', 'US', 0, 0, 'up'),
  ('ATO', 'Atmos Energy', 'energy', 'US', 0, 0, 'up'),
  ('ADSK', 'Autodesk', 'tech', 'US', 0, 0, 'up'),
  ('ADP', 'Automatic Data Processing', 'macro', 'US', 0, 0, 'up'),
  ('AZO', 'AutoZone', 'macro', 'US', 0, 0, 'up'),
  ('AVB', 'AvalonBay Communities', 'finance', 'US', 0, 0, 'up'),
  ('AVY', 'Avery Dennison', 'energy', 'US', 0, 0, 'up'),
  ('AXON', 'Axon Enterprise', 'macro', 'US', 0, 0, 'up'),
  ('BKR', 'Baker Hughes', 'energy', 'US', 0, 0, 'up'),
  ('BALL', 'Ball Corporation', 'energy', 'US', 0, 0, 'up'),
  ('BAC', 'Bank of America', 'finance', 'US', 0, 0, 'up'),
  ('BAX', 'Baxter International', 'macro', 'US', 0, 0, 'up'),
  ('BDX', 'Becton Dickinson', 'macro', 'US', 0, 0, 'up'),
  ('BRK-B', 'Berkshire Hathaway', 'finance', 'US', 0, 0, 'up'),
  ('BBY', 'Best Buy', 'macro', 'US', 0, 0, 'up'),
  ('TECH', 'Bio-Techne', 'macro', 'US', 0, 0, 'up'),
  ('BIIB', 'Biogen', 'macro', 'US', 0, 0, 'up'),
  ('BLK', 'BlackRock', 'finance', 'US', 0, 0, 'up'),
  ('BX', 'Blackstone Inc.', 'finance', 'US', 0, 0, 'up'),
  ('XYZ', 'Block, Inc.', 'finance', 'US', 0, 0, 'up'),
  ('BNY', 'BNY Mellon', 'finance', 'US', 0, 0, 'up'),
  ('BA', 'Boeing', 'macro', 'US', 0, 0, 'up'),
  ('BKNG', 'Booking Holdings', 'macro', 'US', 0, 0, 'up'),
  ('BSX', 'Boston Scientific', 'macro', 'US', 0, 0, 'up'),
  ('BMY', 'Bristol Myers Squibb', 'macro', 'US', 0, 0, 'up'),
  ('AVGO', 'Broadcom', 'tech', 'US', 0, 0, 'up'),
  ('BR', 'Broadridge Financial Solutions', 'macro', 'US', 0, 0, 'up'),
  ('BRO', 'Brown & Brown', 'finance', 'US', 0, 0, 'up'),
  ('BF-B', 'Brown–Forman', 'macro', 'US', 0, 0, 'up'),
  ('BLDR', 'Builders FirstSource', 'macro', 'US', 0, 0, 'up'),
  ('BG', 'Bunge Global', 'macro', 'US', 0, 0, 'up'),
  ('BXP', 'BXP, Inc.', 'finance', 'US', 0, 0, 'up'),
  ('CHRW', 'C.H. Robinson', 'macro', 'US', 0, 0, 'up'),
  ('CDNS', 'Cadence Design Systems', 'tech', 'US', 0, 0, 'up'),
  ('CPT', 'Camden Property Trust', 'finance', 'US', 0, 0, 'up'),
  ('COF', 'Capital One', 'finance', 'US', 0, 0, 'up'),
  ('CAH', 'Cardinal Health', 'macro', 'US', 0, 0, 'up'),
  ('CCL', 'Carnival Corporation', 'macro', 'US', 0, 0, 'up'),
  ('CARR', 'Carrier Global', 'macro', 'US', 0, 0, 'up'),
  ('CVNA', 'Carvana', 'macro', 'US', 0, 0, 'up'),
  ('CASY', 'Casey''s', 'macro', 'US', 0, 0, 'up'),
  ('CAT', 'Caterpillar Inc.', 'macro', 'US', 0, 0, 'up'),
  ('CBOE', 'Cboe Global Markets', 'finance', 'US', 0, 0, 'up'),
  ('CBRE', 'CBRE Group', 'finance', 'US', 0, 0, 'up'),
  ('CDW', 'CDW Corporation', 'tech', 'US', 0, 0, 'up'),
  ('COR', 'Cencora', 'macro', 'US', 0, 0, 'up'),
  ('CNC', 'Centene Corporation', 'macro', 'US', 0, 0, 'up'),
  ('CNP', 'CenterPoint Energy', 'energy', 'US', 0, 0, 'up'),
  ('CF', 'CF Industries', 'energy', 'US', 0, 0, 'up'),
  ('CRL', 'Charles River Laboratories', 'macro', 'US', 0, 0, 'up'),
  ('SCHW', 'Charles Schwab Corporation', 'finance', 'US', 0, 0, 'up'),
  ('CHTR', 'Charter Communications', 'tech', 'US', 0, 0, 'up'),
  ('CVX', 'Chevron Corporation', 'energy', 'US', 0, 0, 'up'),
  ('CMG', 'Chipotle Mexican Grill', 'macro', 'US', 0, 0, 'up'),
  ('CB', 'Chubb Limited', 'finance', 'US', 0, 0, 'up'),
  ('CHD', 'Church & Dwight', 'macro', 'US', 0, 0, 'up'),
  ('CIEN', 'Ciena', 'tech', 'US', 0, 0, 'up'),
  ('CI', 'Cigna', 'macro', 'US', 0, 0, 'up'),
  ('CINF', 'Cincinnati Financial', 'finance', 'US', 0, 0, 'up'),
  ('CTAS', 'Cintas', 'macro', 'US', 0, 0, 'up'),
  ('CSCO', 'Cisco', 'tech', 'US', 0, 0, 'up'),
  ('C', 'Citigroup', 'finance', 'US', 0, 0, 'up'),
  ('CFG', 'Citizens Financial Group', 'finance', 'US', 0, 0, 'up'),
  ('CLX', 'Clorox', 'macro', 'US', 0, 0, 'up'),
  ('CME', 'CME Group', 'finance', 'US', 0, 0, 'up'),
  ('CMS', 'CMS Energy', 'energy', 'US', 0, 0, 'up'),
  ('KO', 'Coca-Cola Company (The)', 'macro', 'US', 0, 0, 'up'),
  ('CTSH', 'Cognizant', 'tech', 'US', 0, 0, 'up'),
  ('COHR', 'Coherent Corp.', 'tech', 'US', 0, 0, 'up'),
  ('COIN', 'Coinbase', 'finance', 'US', 0, 0, 'up'),
  ('CL', 'Colgate-Palmolive', 'macro', 'US', 0, 0, 'up'),
  ('CMCSA', 'Comcast', 'tech', 'US', 0, 0, 'up'),
  ('FIX', 'Comfort Systems USA', 'macro', 'US', 0, 0, 'up'),
  ('COP', 'ConocoPhillips', 'energy', 'US', 0, 0, 'up'),
  ('ED', 'Consolidated Edison', 'energy', 'US', 0, 0, 'up'),
  ('STZ', 'Constellation Brands', 'macro', 'US', 0, 0, 'up'),
  ('CEG', 'Constellation Energy', 'energy', 'US', 0, 0, 'up'),
  ('COO', 'Cooper Companies (The)', 'macro', 'US', 0, 0, 'up'),
  ('CPRT', 'Copart', 'macro', 'US', 0, 0, 'up'),
  ('GLW', 'Corning Inc.', 'tech', 'US', 0, 0, 'up'),
  ('CPAY', 'Corpay', 'finance', 'US', 0, 0, 'up'),
  ('CTVA', 'Corteva', 'energy', 'US', 0, 0, 'up'),
  ('CSGP', 'CoStar Group', 'finance', 'US', 0, 0, 'up'),
  ('COST', 'Costco', 'macro', 'US', 0, 0, 'up'),
  ('CRH', 'CRH plc', 'energy', 'US', 0, 0, 'up'),
  ('CRWD', 'CrowdStrike', 'tech', 'US', 0, 0, 'up'),
  ('CCI', 'Crown Castle', 'finance', 'US', 0, 0, 'up'),
  ('CSX', 'CSX Corporation', 'macro', 'US', 0, 0, 'up'),
  ('CMI', 'Cummins', 'macro', 'US', 0, 0, 'up'),
  ('CVS', 'CVS Health', 'macro', 'US', 0, 0, 'up'),
  ('DHR', 'Danaher Corporation', 'macro', 'US', 0, 0, 'up'),
  ('DRI', 'Darden Restaurants', 'macro', 'US', 0, 0, 'up'),
  ('DDOG', 'Datadog', 'tech', 'US', 0, 0, 'up'),
  ('DVA', 'DaVita', 'macro', 'US', 0, 0, 'up'),
  ('DECK', 'Deckers Brands', 'macro', 'US', 0, 0, 'up'),
  ('DE', 'Deere & Company', 'macro', 'US', 0, 0, 'up'),
  ('DELL', 'Dell Technologies', 'tech', 'US', 0, 0, 'up'),
  ('DAL', 'Delta Air Lines', 'macro', 'US', 0, 0, 'up'),
  ('DVN', 'Devon Energy', 'energy', 'US', 0, 0, 'up'),
  ('DXCM', 'Dexcom', 'macro', 'US', 0, 0, 'up'),
  ('FANG', 'Diamondback Energy', 'energy', 'US', 0, 0, 'up'),
  ('DLR', 'Digital Realty', 'finance', 'US', 0, 0, 'up'),
  ('DG', 'Dollar General', 'macro', 'US', 0, 0, 'up'),
  ('DLTR', 'Dollar Tree', 'macro', 'US', 0, 0, 'up'),
  ('D', 'Dominion Energy', 'energy', 'US', 0, 0, 'up'),
  ('DPZ', 'Domino''s', 'macro', 'US', 0, 0, 'up'),
  ('DASH', 'DoorDash', 'macro', 'US', 0, 0, 'up'),
  ('DOV', 'Dover Corporation', 'macro', 'US', 0, 0, 'up'),
  ('DOW', 'Dow Inc.', 'energy', 'US', 0, 0, 'up'),
  ('DHI', 'D. R. Horton', 'macro', 'US', 0, 0, 'up'),
  ('DTE', 'DTE Energy', 'energy', 'US', 0, 0, 'up'),
  ('DUK', 'Duke Energy', 'energy', 'US', 0, 0, 'up'),
  ('DD', 'DuPont', 'energy', 'US', 0, 0, 'up'),
  ('ETN', 'Eaton Corporation', 'macro', 'US', 0, 0, 'up'),
  ('EBAY', 'eBay Inc.', 'macro', 'US', 0, 0, 'up'),
  ('ECHO', 'EchoStar', 'tech', 'US', 0, 0, 'up'),
  ('ECL', 'Ecolab', 'energy', 'US', 0, 0, 'up'),
  ('EIX', 'Edison International', 'energy', 'US', 0, 0, 'up'),
  ('EW', 'Edwards Lifesciences', 'macro', 'US', 0, 0, 'up'),
  ('EA', 'Electronic Arts', 'tech', 'US', 0, 0, 'up'),
  ('ELV', 'Elevance Health', 'macro', 'US', 0, 0, 'up'),
  ('EME', 'Emcor', 'macro', 'US', 0, 0, 'up'),
  ('EMR', 'Emerson Electric', 'macro', 'US', 0, 0, 'up'),
  ('ETR', 'Entergy', 'energy', 'US', 0, 0, 'up'),
  ('EOG', 'EOG Resources', 'energy', 'US', 0, 0, 'up'),
  ('EQT', 'EQT Corporation', 'energy', 'US', 0, 0, 'up'),
  ('EFX', 'Equifax', 'macro', 'US', 0, 0, 'up'),
  ('EQIX', 'Equinix', 'finance', 'US', 0, 0, 'up'),
  ('EQR', 'Equity Residential', 'finance', 'US', 0, 0, 'up'),
  ('ERIE', 'Erie Indemnity', 'finance', 'US', 0, 0, 'up'),
  ('ESS', 'Essex Property Trust', 'finance', 'US', 0, 0, 'up'),
  ('EL', 'Estée Lauder Companies (The)', 'macro', 'US', 0, 0, 'up'),
  ('EG', 'Everest Group', 'finance', 'US', 0, 0, 'up'),
  ('EVRG', 'Evergy', 'energy', 'US', 0, 0, 'up'),
  ('ES', 'Eversource Energy', 'energy', 'US', 0, 0, 'up'),
  ('EXC', 'Exelon', 'energy', 'US', 0, 0, 'up'),
  ('EXE', 'Expand Energy', 'energy', 'US', 0, 0, 'up'),
  ('EXPE', 'Expedia Group', 'macro', 'US', 0, 0, 'up'),
  ('EXPD', 'Expeditors International', 'macro', 'US', 0, 0, 'up'),
  ('EXR', 'Extra Space Storage', 'finance', 'US', 0, 0, 'up'),
  ('XOM', 'ExxonMobil', 'energy', 'US', 0, 0, 'up'),
  ('FFIV', 'F5, Inc.', 'tech', 'US', 0, 0, 'up'),
  ('FDS', 'FactSet', 'finance', 'US', 0, 0, 'up'),
  ('FICO', 'Fair Isaac', 'tech', 'US', 0, 0, 'up'),
  ('FAST', 'Fastenal', 'macro', 'US', 0, 0, 'up'),
  ('FRT', 'Federal Realty Investment Trust', 'finance', 'US', 0, 0, 'up'),
  ('FDX', 'FedEx', 'macro', 'US', 0, 0, 'up'),
  ('FDXF', 'FedEx Freight', 'macro', 'US', 0, 0, 'up'),
  ('FIS', 'Fidelity National Information Services', 'finance', 'US', 0, 0, 'up'),
  ('FITB', 'Fifth Third Bancorp', 'finance', 'US', 0, 0, 'up'),
  ('FSLR', 'First Solar', 'tech', 'US', 0, 0, 'up'),
  ('FE', 'FirstEnergy', 'energy', 'US', 0, 0, 'up'),
  ('FISV', 'Fiserv', 'finance', 'US', 0, 0, 'up'),
  ('FLEX', 'Flex Ltd.', 'tech', 'US', 0, 0, 'up'),
  ('F', 'Ford Motor Company', 'macro', 'US', 0, 0, 'up'),
  ('FTNT', 'Fortinet', 'tech', 'US', 0, 0, 'up'),
  ('FTV', 'Fortive', 'macro', 'US', 0, 0, 'up'),
  ('FOXA', 'Fox Corporation (Class A)', 'tech', 'US', 0, 0, 'up'),
  ('FOX', 'Fox Corporation (Class B)', 'tech', 'US', 0, 0, 'up'),
  ('BEN', 'Franklin Resources', 'finance', 'US', 0, 0, 'up'),
  ('FCX', 'Freeport-McMoRan', 'energy', 'US', 0, 0, 'up'),
  ('GRMN', 'Garmin', 'macro', 'US', 0, 0, 'up'),
  ('IT', 'Gartner', 'tech', 'US', 0, 0, 'up'),
  ('GE', 'GE Aerospace', 'macro', 'US', 0, 0, 'up'),
  ('GEHC', 'GE HealthCare', 'macro', 'US', 0, 0, 'up'),
  ('GEV', 'GE Vernova', 'macro', 'US', 0, 0, 'up'),
  ('GEN', 'Gen Digital', 'tech', 'US', 0, 0, 'up'),
  ('GNRC', 'Generac', 'macro', 'US', 0, 0, 'up'),
  ('GD', 'General Dynamics', 'macro', 'US', 0, 0, 'up'),
  ('GIS', 'General Mills', 'macro', 'US', 0, 0, 'up'),
  ('GM', 'General Motors', 'macro', 'US', 0, 0, 'up'),
  ('GPC', 'Genuine Parts Company', 'macro', 'US', 0, 0, 'up'),
  ('GILD', 'Gilead Sciences', 'macro', 'US', 0, 0, 'up'),
  ('GPN', 'Global Payments', 'finance', 'US', 0, 0, 'up'),
  ('GL', 'Globe Life', 'finance', 'US', 0, 0, 'up'),
  ('GDDY', 'GoDaddy', 'tech', 'US', 0, 0, 'up'),
  ('GS', 'Goldman Sachs', 'finance', 'US', 0, 0, 'up'),
  ('HAL', 'Halliburton', 'energy', 'US', 0, 0, 'up'),
  ('HIG', 'Hartford (The)', 'finance', 'US', 0, 0, 'up'),
  ('HAS', 'Hasbro', 'macro', 'US', 0, 0, 'up'),
  ('HCA', 'HCA Healthcare', 'macro', 'US', 0, 0, 'up'),
  ('DOC', 'Healthpeak Properties', 'finance', 'US', 0, 0, 'up'),
  ('HSIC', 'Henry Schein', 'macro', 'US', 0, 0, 'up'),
  ('HSY', 'Hershey Company (The)', 'macro', 'US', 0, 0, 'up'),
  ('HPE', 'Hewlett Packard Enterprise', 'tech', 'US', 0, 0, 'up'),
  ('HLT', 'Hilton Worldwide', 'macro', 'US', 0, 0, 'up'),
  ('HD', 'Home Depot (The)', 'macro', 'US', 0, 0, 'up'),
  ('HONA', 'Honeywell Aerospace', 'macro', 'US', 0, 0, 'up'),
  ('HON', 'Honeywell Technologies', 'macro', 'US', 0, 0, 'up'),
  ('HRL', 'Hormel Foods', 'macro', 'US', 0, 0, 'up'),
  ('HST', 'Host Hotels & Resorts', 'finance', 'US', 0, 0, 'up'),
  ('HWM', 'Howmet Aerospace', 'macro', 'US', 0, 0, 'up'),
  ('HPQ', 'HP Inc.', 'tech', 'US', 0, 0, 'up'),
  ('HUBB', 'Hubbell Incorporated', 'macro', 'US', 0, 0, 'up'),
  ('HUM', 'Humana', 'macro', 'US', 0, 0, 'up'),
  ('HBAN', 'Huntington Bancshares', 'finance', 'US', 0, 0, 'up'),
  ('HII', 'Huntington Ingalls Industries', 'macro', 'US', 0, 0, 'up'),
  ('IBM', 'IBM', 'tech', 'US', 0, 0, 'up'),
  ('IEX', 'IDEX Corporation', 'macro', 'US', 0, 0, 'up'),
  ('IDXX', 'Idexx Laboratories', 'macro', 'US', 0, 0, 'up'),
  ('ITW', 'Illinois Tool Works', 'macro', 'US', 0, 0, 'up'),
  ('INCY', 'Incyte', 'macro', 'US', 0, 0, 'up'),
  ('IR', 'Ingersoll Rand', 'macro', 'US', 0, 0, 'up'),
  ('PODD', 'Insulet Corporation', 'macro', 'US', 0, 0, 'up'),
  ('INTC', 'Intel', 'tech', 'US', 0, 0, 'up'),
  ('IBKR', 'Interactive Brokers', 'finance', 'US', 0, 0, 'up'),
  ('ICE', 'Intercontinental Exchange', 'finance', 'US', 0, 0, 'up'),
  ('IFF', 'International Flavors & Fragrances', 'energy', 'US', 0, 0, 'up'),
  ('IP', 'International Paper', 'energy', 'US', 0, 0, 'up'),
  ('INTU', 'Intuit', 'tech', 'US', 0, 0, 'up'),
  ('ISRG', 'Intuitive Surgical', 'macro', 'US', 0, 0, 'up'),
  ('IVZ', 'Invesco', 'finance', 'US', 0, 0, 'up'),
  ('INVH', 'Invitation Homes', 'finance', 'US', 0, 0, 'up'),
  ('IQV', 'IQVIA', 'macro', 'US', 0, 0, 'up'),
  ('IRM', 'Iron Mountain', 'finance', 'US', 0, 0, 'up'),
  ('JBHT', 'J.B. Hunt', 'macro', 'US', 0, 0, 'up'),
  ('JBL', 'Jabil', 'tech', 'US', 0, 0, 'up'),
  ('JKHY', 'Jack Henry & Associates', 'finance', 'US', 0, 0, 'up'),
  ('J', 'Jacobs Solutions', 'macro', 'US', 0, 0, 'up'),
  ('JNJ', 'Johnson & Johnson', 'macro', 'US', 0, 0, 'up'),
  ('JCI', 'Johnson Controls', 'macro', 'US', 0, 0, 'up'),
  ('JPM', 'JPMorgan Chase', 'finance', 'US', 0, 0, 'up'),
  ('KVUE', 'Kenvue', 'macro', 'US', 0, 0, 'up'),
  ('KDP', 'Keurig Dr Pepper', 'macro', 'US', 0, 0, 'up'),
  ('KEY', 'KeyCorp', 'finance', 'US', 0, 0, 'up'),
  ('KEYS', 'Keysight Technologies', 'tech', 'US', 0, 0, 'up'),
  ('KMB', 'Kimberly-Clark', 'macro', 'US', 0, 0, 'up'),
  ('KIM', 'Kimco Realty', 'finance', 'US', 0, 0, 'up'),
  ('KMI', 'Kinder Morgan', 'energy', 'US', 0, 0, 'up'),
  ('KKR', 'KKR & Co.', 'finance', 'US', 0, 0, 'up'),
  ('KLAC', 'KLA Corporation', 'tech', 'US', 0, 0, 'up'),
  ('KHC', 'Kraft Heinz', 'macro', 'US', 0, 0, 'up'),
  ('KR', 'Kroger', 'macro', 'US', 0, 0, 'up'),
  ('LHX', 'L3Harris', 'macro', 'US', 0, 0, 'up'),
  ('LH', 'Labcorp', 'macro', 'US', 0, 0, 'up'),
  ('LRCX', 'Lam Research', 'tech', 'US', 0, 0, 'up'),
  ('LVS', 'Las Vegas Sands', 'macro', 'US', 0, 0, 'up'),
  ('LDOS', 'Leidos', 'macro', 'US', 0, 0, 'up'),
  ('LEN', 'Lennar', 'macro', 'US', 0, 0, 'up'),
  ('LII', 'Lennox International', 'macro', 'US', 0, 0, 'up'),
  ('LLY', 'Lilly (Eli)', 'macro', 'US', 0, 0, 'up'),
  ('LIN', 'Linde plc', 'energy', 'US', 0, 0, 'up'),
  ('LYV', 'Live Nation Entertainment', 'tech', 'US', 0, 0, 'up'),
  ('LMT', 'Lockheed Martin', 'macro', 'US', 0, 0, 'up'),
  ('L', 'Loews Corporation', 'finance', 'US', 0, 0, 'up'),
  ('LOW', 'Lowe''s', 'macro', 'US', 0, 0, 'up'),
  ('LULU', 'Lululemon Athletica', 'macro', 'US', 0, 0, 'up'),
  ('LITE', 'Lumentum', 'tech', 'US', 0, 0, 'up'),
  ('LYB', 'LyondellBasell', 'energy', 'US', 0, 0, 'up'),
  ('MTB', 'M&T Bank', 'finance', 'US', 0, 0, 'up'),
  ('MPC', 'Marathon Petroleum', 'energy', 'US', 0, 0, 'up'),
  ('MAR', 'Marriott International', 'macro', 'US', 0, 0, 'up'),
  ('MRSH', 'Marsh McLennan', 'finance', 'US', 0, 0, 'up'),
  ('MLM', 'Martin Marietta Materials', 'energy', 'US', 0, 0, 'up'),
  ('MRVL', 'Marvell Technology', 'tech', 'US', 0, 0, 'up'),
  ('MAS', 'Masco', 'macro', 'US', 0, 0, 'up'),
  ('MA', 'Mastercard', 'finance', 'US', 0, 0, 'up'),
  ('MKC', 'McCormick & Company', 'macro', 'US', 0, 0, 'up'),
  ('MCD', 'McDonald''s', 'macro', 'US', 0, 0, 'up'),
  ('MCK', 'McKesson Corporation', 'macro', 'US', 0, 0, 'up'),
  ('MDT', 'Medtronic', 'macro', 'US', 0, 0, 'up'),
  ('MRK', 'Merck & Co.', 'macro', 'US', 0, 0, 'up'),
  ('META', 'Meta Platforms', 'tech', 'US', 0, 0, 'up'),
  ('MET', 'MetLife', 'finance', 'US', 0, 0, 'up'),
  ('MTD', 'Mettler Toledo', 'macro', 'US', 0, 0, 'up'),
  ('MGM', 'MGM Resorts', 'macro', 'US', 0, 0, 'up'),
  ('MCHP', 'Microchip Technology', 'tech', 'US', 0, 0, 'up'),
  ('MU', 'Micron Technology', 'tech', 'US', 0, 0, 'up'),
  ('MSFT', 'Microsoft', 'tech', 'US', 0, 0, 'up'),
  ('MAA', 'Mid-America Apartment Communities', 'finance', 'US', 0, 0, 'up'),
  ('MRNA', 'Moderna', 'macro', 'US', 0, 0, 'up'),
  ('TAP', 'Molson Coors Beverage Company', 'macro', 'US', 0, 0, 'up'),
  ('MDLZ', 'Mondelez International', 'macro', 'US', 0, 0, 'up'),
  ('MPWR', 'Monolithic Power Systems', 'tech', 'US', 0, 0, 'up'),
  ('MNST', 'Monster Beverage', 'macro', 'US', 0, 0, 'up'),
  ('MCO', 'Moody''s Corporation', 'finance', 'US', 0, 0, 'up'),
  ('MS', 'Morgan Stanley', 'finance', 'US', 0, 0, 'up'),
  ('MOS', 'Mosaic Company (The)', 'energy', 'US', 0, 0, 'up'),
  ('MSI', 'Motorola Solutions', 'tech', 'US', 0, 0, 'up'),
  ('MSCI', 'MSCI Inc.', 'finance', 'US', 0, 0, 'up'),
  ('NDAQ', 'Nasdaq, Inc.', 'finance', 'US', 0, 0, 'up'),
  ('NTAP', 'NetApp', 'tech', 'US', 0, 0, 'up'),
  ('NFLX', 'Netflix', 'tech', 'US', 0, 0, 'up'),
  ('NEM', 'Newmont', 'energy', 'US', 0, 0, 'up'),
  ('NWSA', 'News Corp (Class A)', 'tech', 'US', 0, 0, 'up'),
  ('NWS', 'News Corp (Class B)', 'tech', 'US', 0, 0, 'up'),
  ('NEE', 'NextEra Energy', 'energy', 'US', 0, 0, 'up'),
  ('NKE', 'Nike, Inc.', 'macro', 'US', 0, 0, 'up'),
  ('NI', 'NiSource', 'energy', 'US', 0, 0, 'up'),
  ('NDSN', 'Nordson Corporation', 'macro', 'US', 0, 0, 'up'),
  ('NSC', 'Norfolk Southern', 'macro', 'US', 0, 0, 'up'),
  ('NTRS', 'Northern Trust', 'finance', 'US', 0, 0, 'up'),
  ('NOC', 'Northrop Grumman', 'macro', 'US', 0, 0, 'up'),
  ('NCLH', 'Norwegian Cruise Line Holdings', 'macro', 'US', 0, 0, 'up'),
  ('NRG', 'NRG Energy', 'energy', 'US', 0, 0, 'up'),
  ('NUE', 'Nucor', 'energy', 'US', 0, 0, 'up'),
  ('NVDA', 'Nvidia', 'tech', 'US', 0, 0, 'up'),
  ('NVR', 'NVR, Inc.', 'macro', 'US', 0, 0, 'up'),
  ('NXPI', 'NXP Semiconductors', 'tech', 'US', 0, 0, 'up'),
  ('ORLY', 'O’Reilly Automotive', 'macro', 'US', 0, 0, 'up'),
  ('OXY', 'Occidental Petroleum', 'energy', 'US', 0, 0, 'up'),
  ('ODFL', 'Old Dominion', 'macro', 'US', 0, 0, 'up'),
  ('OMC', 'Omnicom Group', 'tech', 'US', 0, 0, 'up'),
  ('ON', 'ON Semiconductor', 'tech', 'US', 0, 0, 'up'),
  ('OKE', 'Oneok', 'energy', 'US', 0, 0, 'up'),
  ('ORCL', 'Oracle Corporation', 'tech', 'US', 0, 0, 'up'),
  ('OTIS', 'Otis Worldwide', 'macro', 'US', 0, 0, 'up'),
  ('PCAR', 'Paccar', 'macro', 'US', 0, 0, 'up'),
  ('PKG', 'Packaging Corporation of America', 'energy', 'US', 0, 0, 'up'),
  ('PLTR', 'Palantir Technologies', 'tech', 'US', 0, 0, 'up'),
  ('PANW', 'Palo Alto Networks', 'tech', 'US', 0, 0, 'up'),
  ('PSKY', 'Paramount Skydance Corporation', 'tech', 'US', 0, 0, 'up'),
  ('PH', 'Parker Hannifin', 'macro', 'US', 0, 0, 'up'),
  ('PAYX', 'Paychex', 'macro', 'US', 0, 0, 'up'),
  ('PYPL', 'PayPal', 'finance', 'US', 0, 0, 'up'),
  ('PNR', 'Pentair', 'macro', 'US', 0, 0, 'up'),
  ('PEP', 'PepsiCo', 'macro', 'US', 0, 0, 'up'),
  ('PFE', 'Pfizer', 'macro', 'US', 0, 0, 'up'),
  ('PCG', 'PG&E Corporation', 'energy', 'US', 0, 0, 'up'),
  ('PM', 'Philip Morris International', 'macro', 'US', 0, 0, 'up'),
  ('PSX', 'Phillips 66', 'energy', 'US', 0, 0, 'up'),
  ('PNW', 'Pinnacle West Capital', 'energy', 'US', 0, 0, 'up'),
  ('PNC', 'PNC Financial Services', 'finance', 'US', 0, 0, 'up'),
  ('PPG', 'PPG Industries', 'energy', 'US', 0, 0, 'up'),
  ('PPL', 'PPL Corporation', 'energy', 'US', 0, 0, 'up'),
  ('PFG', 'Principal Financial Group', 'finance', 'US', 0, 0, 'up'),
  ('PG', 'Procter & Gamble', 'macro', 'US', 0, 0, 'up'),
  ('PGR', 'Progressive Corporation', 'finance', 'US', 0, 0, 'up'),
  ('PLD', 'Prologis', 'finance', 'US', 0, 0, 'up'),
  ('PRU', 'Prudential Financial', 'finance', 'US', 0, 0, 'up'),
  ('PEG', 'Public Service Enterprise Group', 'energy', 'US', 0, 0, 'up'),
  ('PTC', 'PTC Inc.', 'tech', 'US', 0, 0, 'up'),
  ('PSA', 'Public Storage', 'finance', 'US', 0, 0, 'up'),
  ('PHM', 'PulteGroup', 'macro', 'US', 0, 0, 'up'),
  ('PWR', 'Quanta Services', 'macro', 'US', 0, 0, 'up'),
  ('QCOM', 'Qualcomm', 'tech', 'US', 0, 0, 'up'),
  ('DGX', 'Quest Diagnostics', 'macro', 'US', 0, 0, 'up'),
  ('Q', 'Qnity Electronics', 'tech', 'US', 0, 0, 'up'),
  ('RL', 'Ralph Lauren Corporation', 'macro', 'US', 0, 0, 'up'),
  ('RJF', 'Raymond James Financial', 'finance', 'US', 0, 0, 'up'),
  ('RTX', 'RTX Corporation', 'macro', 'US', 0, 0, 'up'),
  ('O', 'Realty Income', 'finance', 'US', 0, 0, 'up'),
  ('REG', 'Regency Centers', 'finance', 'US', 0, 0, 'up'),
  ('REGN', 'Regeneron Pharmaceuticals', 'macro', 'US', 0, 0, 'up'),
  ('RF', 'Regions Financial Corporation', 'finance', 'US', 0, 0, 'up'),
  ('RSG', 'Republic Services', 'macro', 'US', 0, 0, 'up'),
  ('RMD', 'ResMed', 'macro', 'US', 0, 0, 'up'),
  ('RVTY', 'Revvity', 'macro', 'US', 0, 0, 'up'),
  ('HOOD', 'Robinhood Markets', 'finance', 'US', 0, 0, 'up'),
  ('ROK', 'Rockwell Automation', 'macro', 'US', 0, 0, 'up'),
  ('ROL', 'Rollins, Inc.', 'macro', 'US', 0, 0, 'up'),
  ('ROP', 'Roper Technologies', 'tech', 'US', 0, 0, 'up'),
  ('ROST', 'Ross Stores', 'macro', 'US', 0, 0, 'up'),
  ('RCL', 'Royal Caribbean Group', 'macro', 'US', 0, 0, 'up'),
  ('SPGI', 'S&P Global', 'finance', 'US', 0, 0, 'up'),
  ('CRM', 'Salesforce', 'tech', 'US', 0, 0, 'up'),
  ('SNDK', 'Sandisk', 'tech', 'US', 0, 0, 'up'),
  ('SBAC', 'SBA Communications', 'finance', 'US', 0, 0, 'up'),
  ('SLB', 'Schlumberger', 'energy', 'US', 0, 0, 'up'),
  ('STX', 'Seagate Technology', 'tech', 'US', 0, 0, 'up'),
  ('SRE', 'Sempra', 'energy', 'US', 0, 0, 'up'),
  ('NOW', 'ServiceNow', 'tech', 'US', 0, 0, 'up'),
  ('SHW', 'Sherwin-Williams', 'energy', 'US', 0, 0, 'up'),
  ('SPG', 'Simon Property Group', 'finance', 'US', 0, 0, 'up'),
  ('SWKS', 'Skyworks Solutions', 'tech', 'US', 0, 0, 'up'),
  ('SJM', 'J.M. Smucker Company (The)', 'macro', 'US', 0, 0, 'up'),
  ('SW', 'Smurfit Westrock', 'energy', 'US', 0, 0, 'up'),
  ('SNA', 'Snap-on', 'macro', 'US', 0, 0, 'up'),
  ('SOLV', 'Solventum', 'macro', 'US', 0, 0, 'up'),
  ('SO', 'Southern Company', 'energy', 'US', 0, 0, 'up'),
  ('LUV', 'Southwest Airlines', 'macro', 'US', 0, 0, 'up'),
  ('SWK', 'Stanley Black & Decker', 'macro', 'US', 0, 0, 'up'),
  ('SBUX', 'Starbucks', 'macro', 'US', 0, 0, 'up'),
  ('STT', 'State Street Corporation', 'finance', 'US', 0, 0, 'up'),
  ('STLD', 'Steel Dynamics', 'energy', 'US', 0, 0, 'up'),
  ('STE', 'Steris', 'macro', 'US', 0, 0, 'up'),
  ('SYK', 'Stryker Corporation', 'macro', 'US', 0, 0, 'up'),
  ('SMCI', 'Supermicro', 'tech', 'US', 0, 0, 'up'),
  ('SYF', 'Synchrony Financial', 'finance', 'US', 0, 0, 'up'),
  ('SNPS', 'Synopsys', 'tech', 'US', 0, 0, 'up'),
  ('SYY', 'Sysco', 'macro', 'US', 0, 0, 'up'),
  ('TMUS', 'T-Mobile US', 'tech', 'US', 0, 0, 'up'),
  ('TROW', 'T. Rowe Price', 'finance', 'US', 0, 0, 'up'),
  ('TTWO', 'Take-Two Interactive', 'tech', 'US', 0, 0, 'up'),
  ('TPR', 'Tapestry, Inc.', 'macro', 'US', 0, 0, 'up'),
  ('TRGP', 'Targa Resources', 'energy', 'US', 0, 0, 'up'),
  ('TGT', 'Target Corporation', 'macro', 'US', 0, 0, 'up'),
  ('TEL', 'TE Connectivity', 'tech', 'US', 0, 0, 'up'),
  ('TDY', 'Teledyne Technologies', 'tech', 'US', 0, 0, 'up'),
  ('TER', 'Teradyne', 'tech', 'US', 0, 0, 'up'),
  ('TSLA', 'Tesla, Inc.', 'macro', 'US', 0, 0, 'up'),
  ('TXN', 'Texas Instruments', 'tech', 'US', 0, 0, 'up'),
  ('TPL', 'Texas Pacific Land Corporation', 'energy', 'US', 0, 0, 'up'),
  ('TXT', 'Textron', 'macro', 'US', 0, 0, 'up'),
  ('TMO', 'Thermo Fisher Scientific', 'macro', 'US', 0, 0, 'up'),
  ('TJX', 'TJX Companies', 'macro', 'US', 0, 0, 'up'),
  ('TKO', 'TKO Group Holdings', 'tech', 'US', 0, 0, 'up'),
  ('TTD', 'Trade Desk (The)', 'tech', 'US', 0, 0, 'up'),
  ('TSCO', 'Tractor Supply', 'macro', 'US', 0, 0, 'up'),
  ('TT', 'Trane Technologies', 'macro', 'US', 0, 0, 'up'),
  ('TDG', 'TransDigm Group', 'macro', 'US', 0, 0, 'up'),
  ('TRV', 'Travelers Companies (The)', 'finance', 'US', 0, 0, 'up'),
  ('TRMB', 'Trimble Inc.', 'tech', 'US', 0, 0, 'up'),
  ('TFC', 'Truist Financial', 'finance', 'US', 0, 0, 'up'),
  ('TYL', 'Tyler Technologies', 'tech', 'US', 0, 0, 'up'),
  ('TSN', 'Tyson Foods', 'macro', 'US', 0, 0, 'up'),
  ('USB', 'U.S. Bancorp', 'finance', 'US', 0, 0, 'up'),
  ('UBER', 'Uber', 'macro', 'US', 0, 0, 'up'),
  ('UDR', 'UDR, Inc.', 'finance', 'US', 0, 0, 'up'),
  ('ULTA', 'Ulta Beauty', 'macro', 'US', 0, 0, 'up'),
  ('UNP', 'Union Pacific Corporation', 'macro', 'US', 0, 0, 'up'),
  ('UAL', 'United Airlines Holdings', 'macro', 'US', 0, 0, 'up'),
  ('UPS', 'United Parcel Service', 'macro', 'US', 0, 0, 'up'),
  ('URI', 'United Rentals', 'macro', 'US', 0, 0, 'up'),
  ('UNH', 'UnitedHealth Group', 'macro', 'US', 0, 0, 'up'),
  ('UHS', 'Universal Health Services', 'macro', 'US', 0, 0, 'up'),
  ('VLO', 'Valero Energy', 'energy', 'US', 0, 0, 'up'),
  ('VEEV', 'Veeva Systems', 'macro', 'US', 0, 0, 'up'),
  ('VTR', 'Ventas', 'finance', 'US', 0, 0, 'up'),
  ('VLTO', 'Veralto', 'macro', 'US', 0, 0, 'up'),
  ('VRSN', 'Verisign', 'tech', 'US', 0, 0, 'up'),
  ('VRSK', 'Verisk Analytics', 'macro', 'US', 0, 0, 'up'),
  ('VZ', 'Verizon', 'tech', 'US', 0, 0, 'up'),
  ('VRTX', 'Vertex Pharmaceuticals', 'macro', 'US', 0, 0, 'up'),
  ('VRT', 'Vertiv', 'macro', 'US', 0, 0, 'up'),
  ('VTRS', 'Viatris', 'macro', 'US', 0, 0, 'up'),
  ('VICI', 'Vici Properties', 'finance', 'US', 0, 0, 'up'),
  ('V', 'Visa Inc.', 'finance', 'US', 0, 0, 'up'),
  ('VST', 'Vistra Corp .', 'energy', 'US', 0, 0, 'up'),
  ('VMC', 'Vulcan Materials Company', 'energy', 'US', 0, 0, 'up'),
  ('WRB', 'W. R. Berkley Corporation', 'finance', 'US', 0, 0, 'up'),
  ('GWW', 'W. W. Grainger', 'macro', 'US', 0, 0, 'up'),
  ('WAB', 'Wabtec', 'macro', 'US', 0, 0, 'up'),
  ('WMT', 'Walmart', 'macro', 'US', 0, 0, 'up'),
  ('DIS', 'Walt Disney Company (The)', 'tech', 'US', 0, 0, 'up'),
  ('WBD', 'Warner Bros. Discovery', 'tech', 'US', 0, 0, 'up'),
  ('WM', 'Waste Management', 'macro', 'US', 0, 0, 'up'),
  ('WAT', 'Waters Corporation', 'macro', 'US', 0, 0, 'up'),
  ('WEC', 'WEC Energy Group', 'energy', 'US', 0, 0, 'up'),
  ('WFC', 'Wells Fargo', 'finance', 'US', 0, 0, 'up'),
  ('WELL', 'Welltower', 'finance', 'US', 0, 0, 'up'),
  ('WST', 'West Pharmaceutical Services', 'macro', 'US', 0, 0, 'up'),
  ('WDC', 'Western Digital', 'tech', 'US', 0, 0, 'up'),
  ('WY', 'Weyerhaeuser', 'finance', 'US', 0, 0, 'up'),
  ('WSM', 'Williams-Sonoma, Inc.', 'macro', 'US', 0, 0, 'up'),
  ('WMB', 'Williams Companies', 'energy', 'US', 0, 0, 'up'),
  ('WTW', 'Willis Towers Watson', 'finance', 'US', 0, 0, 'up'),
  ('WDAY', 'Workday, Inc.', 'tech', 'US', 0, 0, 'up'),
  ('WYNN', 'Wynn Resorts', 'macro', 'US', 0, 0, 'up'),
  ('XEL', 'Xcel Energy', 'energy', 'US', 0, 0, 'up'),
  ('XYL', 'Xylem Inc.', 'macro', 'US', 0, 0, 'up'),
  ('YUM', 'Yum! Brands', 'macro', 'US', 0, 0, 'up'),
  ('ZBRA', 'Zebra Technologies', 'tech', 'US', 0, 0, 'up'),
  ('ZBH', 'Zimmer Biomet', 'macro', 'US', 0, 0, 'up'),
  ('ZTS', 'Zoetis', 'macro', 'US', 0, 0, 'up')
ON CONFLICT (symbol) DO NOTHING;
