export type TickerInfo = {
  symbol: string
  name: string
  sector: string
  aliases: readonly string[]
}

export const TOP100_TICKERS_DATA: readonly TickerInfo[] = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "tech", aliases: ["Apple", "iPhone", "Mac", "iPad", "AAPL", "Tim Cook"] },
  { symbol: "MSFT", name: "Microsoft Corp.", sector: "tech", aliases: ["Microsoft", "Azure", "Windows", "Office", "MSFT", "Satya Nadella"] },
  { symbol: "NVDA", name: "Nvidia Corp.", sector: "tech", aliases: ["Nvidia", "GeForce", "CUDA", "NVDA", "Jensen Huang"] },
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "tech", aliases: ["Amazon", "AWS", "Prime", "AMZN", "Andy Jassy"] },
  { symbol: "GOOGL", name: "Alphabet Inc.", sector: "tech", aliases: ["Alphabet", "Google", "YouTube", "DeepMind", "GOOGL", "GOOG", "Sundar Pichai"] },
  { symbol: "META", name: "Meta Platforms Inc.", sector: "tech", aliases: ["Meta", "Facebook", "Instagram", "WhatsApp", "META", "Mark Zuckerberg"] },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "consumer", aliases: ["Tesla", "Elon Musk", "TSLA", "Cybertruck"] },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc.", sector: "finance", aliases: ["Berkshire Hathaway", "Berkshire", "Warren Buffett", "BRK.B", "BRK-B", "Buffett"] },
  { symbol: "LLY", name: "Eli Lilly and Co.", sector: "healthcare", aliases: ["Eli Lilly", "Lilly", "LLY", "Zepbound", "Mounjaro"] },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "tech", aliases: ["Broadcom", "AVGO", "Hock Tan"] },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "finance", aliases: ["JPMorgan", "JPMorgan Chase", "JPM", "Jamie Dimon"] },
  { symbol: "WMT", name: "Walmart Inc.", sector: "consumer", aliases: ["Walmart", "WMT", "Doug McMillon"] },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", sector: "healthcare", aliases: ["UnitedHealth", "United Health", "UNH"] },
  { symbol: "V", name: "Visa Inc.", sector: "finance", aliases: ["Visa", "V"] },
  { symbol: "XOM", name: "Exxon Mobil Corp.", sector: "energy", aliases: ["Exxon Mobil", "Exxon", "XOM", "Darren Woods"] },
  { symbol: "MA", name: "Mastercard Inc.", sector: "finance", aliases: ["Mastercard", "MA"] },
  { symbol: "ORCL", name: "Oracle Corp.", sector: "tech", aliases: ["Oracle", "ORCL", "Larry Ellison"] },
  { symbol: "COST", name: "Costco Wholesale Corp.", sector: "consumer", aliases: ["Costco", "COST"] },
  { symbol: "HD", name: "Home Depot Inc.", sector: "consumer", aliases: ["Home Depot", "HD"] },
  { symbol: "PG", name: "Procter & Gamble Co.", sector: "consumer", aliases: ["Procter & Gamble", "P&G", "PG"] },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "healthcare", aliases: ["Johnson & Johnson", "J&J", "JNJ"] },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "tech", aliases: ["Netflix", "NFLX"] },
  { symbol: "BAC", name: "Bank of America Corp.", sector: "finance", aliases: ["Bank of America", "BofA", "BAC", "Brian Moynihan"] },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "healthcare", aliases: ["AbbVie", "ABBV", "Humira"] },
  { symbol: "CRM", name: "Salesforce Inc.", sector: "tech", aliases: ["Salesforce", "CRM", "Marc Benioff"] },
  { symbol: "CVX", name: "Chevron Corp.", sector: "energy", aliases: ["Chevron", "CVX", "Mike Wirth"] },
  { symbol: "WFC", name: "Wells Fargo & Co.", sector: "finance", aliases: ["Wells Fargo", "WFC", "Charlie Scharf"] },
  { symbol: "KO", name: "The Coca-Cola Co.", sector: "consumer", aliases: ["Coca-Cola", "Coke", "KO"] },
  { symbol: "TMUS", name: "T-Mobile US Inc.", sector: "telecom", aliases: ["T-Mobile", "TMUS"] },
  { symbol: "CSCO", name: "Cisco Systems Inc.", sector: "tech", aliases: ["Cisco", "Cisco Systems", "CSCO"] },
  { symbol: "PEP", name: "PepsiCo Inc.", sector: "consumer", aliases: ["PepsiCo", "Pepsi", "PEP"] },
  { symbol: "IBM", name: "International Business Machines Corp.", sector: "tech", aliases: ["IBM", "Arvind Krishna"] },
  { symbol: "MS", name: "Morgan Stanley", sector: "finance", aliases: ["Morgan Stanley", "MS", "Ted Pick"] },
  { symbol: "ACN", name: "Accenture plc", sector: "tech", aliases: ["Accenture", "ACN"] },
  { symbol: "LIN", name: "Linde plc", sector: "materials", aliases: ["Linde", "LIN"] },
  { symbol: "MCD", name: "McDonald's Corp.", sector: "consumer", aliases: ["McDonald's", "McDonalds", "MCD"] },
  { symbol: "DIS", name: "The Walt Disney Co.", sector: "media", aliases: ["Disney", "Walt Disney", "DIS", "Bob Iger"] },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "healthcare", aliases: ["Abbott", "Abbott Laboratories", "ABT"] },
  { symbol: "PM", name: "Philip Morris International Inc.", sector: "consumer", aliases: ["Philip Morris", "PM"] },
  { symbol: "GE", name: "General Electric Co.", sector: "industrials", aliases: ["General Electric", "GE", "GE Aerospace"] },
  { symbol: "INTU", name: "Intuit Inc.", sector: "tech", aliases: ["Intuit", "TurboTax", "QuickBooks", "INTU"] },
  { symbol: "QCOM", name: "Qualcomm Inc.", sector: "tech", aliases: ["Qualcomm", "Snapdragon", "QCOM"] },
  { symbol: "DHR", name: "Danaher Corp.", sector: "healthcare", aliases: ["Danaher", "DHR"] },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "industrials", aliases: ["Caterpillar", "CAT"] },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", sector: "tech", aliases: ["AMD", "Advanced Micro Devices", "Radeon", "Ryzen", "Lisa Su"] },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc.", sector: "healthcare", aliases: ["Vertex", "Vertex Pharmaceuticals", "VRTX"] },
  { symbol: "TXN", name: "Texas Instruments Inc.", sector: "tech", aliases: ["Texas Instruments", "TXN"] },
  { symbol: "BKNG", name: "Booking Holdings Inc.", sector: "consumer", aliases: ["Booking Holdings", "Booking.com", "BKNG", "Priceline"] },
  { symbol: "AMAT", name: "Applied Materials Inc.", sector: "tech", aliases: ["Applied Materials", "AMAT"] },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "healthcare", aliases: ["Pfizer", "PFE", "Albert Bourla"] },
  { symbol: "T", name: "AT&T Inc.", sector: "telecom", aliases: ["AT&T", "T"] },
  { symbol: "NOW", name: "ServiceNow Inc.", sector: "tech", aliases: ["ServiceNow", "NOW", "Bill McDermott"] },
  { symbol: "LOW", name: "Lowe's Companies Inc.", sector: "consumer", aliases: ["Lowe's", "Lowes", "LOW"] },
  { symbol: "AMGN", name: "Amgen Inc.", sector: "healthcare", aliases: ["Amgen", "AMGN"] },
  { symbol: "C", name: "Citigroup Inc.", sector: "finance", aliases: ["Citigroup", "Citi", "C", "Jane Fraser"] },
  { symbol: "SPGI", name: "S&P Global Inc.", sector: "finance", aliases: ["S&P Global", "SPGI"] },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", sector: "healthcare", aliases: ["Intuitive Surgical", "ISRG", "da Vinci"] },
  { symbol: "UNP", name: "Union Pacific Corp.", sector: "industrials", aliases: ["Union Pacific", "UNP"] },
  { symbol: "GS", name: "The Goldman Sachs Group Inc.", sector: "finance", aliases: ["Goldman Sachs", "Goldman", "GS", "David Solomon"] },
  { symbol: "COP", name: "ConocoPhillips", sector: "energy", aliases: ["ConocoPhillips", "COP"] },
  { symbol: "HON", name: "Honeywell International Inc.", sector: "industrials", aliases: ["Honeywell", "HON"] },
  { symbol: "CMCSA", name: "Comcast Corp.", sector: "media", aliases: ["Comcast", "CMCSA", "Xfinity"] },
  { symbol: "RTX", name: "RTX Corp.", sector: "industrials", aliases: ["RTX", "Raytheon", "Pratt & Whitney"] },
  { symbol: "PGR", name: "The Progressive Corp.", sector: "finance", aliases: ["Progressive", "PGR"] },
  { symbol: "TJX", name: "The TJX Companies Inc.", sector: "consumer", aliases: ["TJX", "TJ Maxx", "Marshalls"] },
  { symbol: "EOG", name: "EOG Resources Inc.", sector: "energy", aliases: ["EOG Resources", "EOG"] },
  { symbol: "SCHW", name: "The Charles Schwab Corp.", sector: "finance", aliases: ["Charles Schwab", "Schwab", "SCHW"] },
  { symbol: "SYK", name: "Stryker Corp.", sector: "healthcare", aliases: ["Stryker", "SYK"] },
  { symbol: "BA", name: "The Boeing Co.", sector: "industrials", aliases: ["Boeing", "BA", "737 MAX", "Kelly Ortberg"] },
  { symbol: "ELV", name: "Elevance Health Inc.", sector: "healthcare", aliases: ["Elevance Health", "Anthem", "ELV"] },
  { symbol: "DE", name: "Deere & Co.", sector: "industrials", aliases: ["Deere", "John Deere", "DE"] },
  { symbol: "ADP", name: "Automatic Data Processing Inc.", sector: "tech", aliases: ["ADP"] },
  { symbol: "VZ", name: "Verizon Communications Inc.", sector: "telecom", aliases: ["Verizon", "VZ"] },
  { symbol: "NKE", name: "NIKE Inc.", sector: "consumer", aliases: ["Nike", "NKE", "Air Jordan"] },
  { symbol: "BSX", name: "Boston Scientific Corp.", sector: "healthcare", aliases: ["Boston Scientific", "BSX"] },
  { symbol: "MMC", name: "Marsh & McLennan Companies Inc.", sector: "finance", aliases: ["Marsh McLennan", "Marsh & McLennan", "MMC"] },
  { symbol: "LRCX", name: "Lam Research Corp.", sector: "tech", aliases: ["Lam Research", "LRCX"] },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "tech", aliases: ["Adobe", "Photoshop", "ADBE", "Shantanu Narayen"] },
  { symbol: "BX", name: "Blackstone Inc.", sector: "finance", aliases: ["Blackstone", "BX", "Stephen Schwarzman"] },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", sector: "tech", aliases: ["Palantir", "PLTR", "Palantir Technologies", "Alex Karp"] },
  { symbol: "GILD", name: "Gilead Sciences Inc.", sector: "healthcare", aliases: ["Gilead", "Gilead Sciences", "GILD"] },
  { symbol: "LMT", name: "Lockheed Martin Corp.", sector: "industrials", aliases: ["Lockheed Martin", "Lockheed", "LMT"] },
  { symbol: "MDLZ", name: "Mondelez International Inc.", sector: "consumer", aliases: ["Mondelez", "MDLZ", "Oreo"] },
  { symbol: "MU", name: "Micron Technology Inc.", sector: "tech", aliases: ["Micron", "Micron Technology", "MU"] },
  { symbol: "FI", name: "Fiserv Inc.", sector: "tech", aliases: ["Fiserv", "FI", "FISV"] },
  { symbol: "SBUX", name: "Starbucks Corp.", sector: "consumer", aliases: ["Starbucks", "SBUX", "Brian Niccol"] },
  { symbol: "PANW", name: "Palo Alto Networks Inc.", sector: "tech", aliases: ["Palo Alto Networks", "PANW", "Nikesh Arora"] },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc.", sector: "healthcare", aliases: ["Regeneron", "REGN", "Dupixent"] },
  { symbol: "CB", name: "Chubb Limited", sector: "finance", aliases: ["Chubb", "CB"] },
  { symbol: "CI", name: "The Cigna Group", sector: "healthcare", aliases: ["Cigna", "CI"] },
  { symbol: "UPS", name: "United Parcel Service Inc.", sector: "industrials", aliases: ["UPS", "United Parcel Service", "Carol Tomé"] },
  { symbol: "PH", name: "Parker-Hannifin Corp.", sector: "industrials", aliases: ["Parker Hannifin", "PH"] },
  { symbol: "KMI", name: "Kinder Morgan Inc.", sector: "energy", aliases: ["Kinder Morgan", "KMI"] },
  { symbol: "AMT", name: "American Tower Corp.", sector: "realestate", aliases: ["American Tower", "AMT"] },
  { symbol: "SHW", name: "The Sherwin-Williams Co.", sector: "materials", aliases: ["Sherwin-Williams", "SHW"] },
  { symbol: "MO", name: "Altria Group Inc.", sector: "consumer", aliases: ["Altria", "MO", "Marlboro"] },
  { symbol: "SLB", name: "Schlumberger N.V.", sector: "energy", aliases: ["Schlumberger", "SLB"] },
  { symbol: "CVS", name: "CVS Health Corp.", sector: "healthcare", aliases: ["CVS", "CVS Health"] },
  { symbol: "CDNS", name: "Cadence Design Systems Inc.", sector: "tech", aliases: ["Cadence", "CDNS"] },
  { symbol: "KKR", name: "KKR & Co. Inc.", sector: "finance", aliases: ["KKR"] },
] as const

export const TOP100_SYMBOLS: readonly string[] = TOP100_TICKERS_DATA.map((t) => t.symbol)

export const TOP100_ALIASES: Record<string, readonly string[]> = Object.fromEntries(
  TOP100_TICKERS_DATA.map((t) => [t.symbol, t.aliases])
)
