export type TickerInfo = {
  symbol: string
  name: string
  sector: string
  aliases: readonly string[]
}

export const TOP100_TICKERS_DATA: readonly TickerInfo[] = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "tech", aliases: ["Apple", "iPhone", "Mac", "iPad"] },
  { symbol: "MSFT", name: "Microsoft Corp.", sector: "tech", aliases: ["Microsoft", "Azure", "Windows", "Office"] },
  { symbol: "NVDA", name: "Nvidia Corp.", sector: "tech", aliases: ["Nvidia", "GeForce", "CUDA"] },
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "tech", aliases: ["Amazon", "AWS", "Prime"] },
  { symbol: "GOOGL", name: "Alphabet Inc.", sector: "tech", aliases: ["Alphabet", "Google", "YouTube", "DeepMind"] },
  { symbol: "META", name: "Meta Platforms Inc.", sector: "tech", aliases: ["Meta", "Facebook", "Instagram", "WhatsApp"] },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "consumer", aliases: ["Tesla", "Elon Musk"] },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc.", sector: "finance", aliases: ["Berkshire Hathaway", "Warren Buffett"] },
  { symbol: "LLY", name: "Eli Lilly and Co.", sector: "healthcare", aliases: ["Eli Lilly"] },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "tech", aliases: ["Broadcom"] },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "finance", aliases: ["JPMorgan", "JPMorgan Chase"] },
  { symbol: "WMT", name: "Walmart Inc.", sector: "consumer", aliases: ["Walmart"] },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", sector: "healthcare", aliases: ["UnitedHealth", "United Health"] },
  { symbol: "V", name: "Visa Inc.", sector: "finance", aliases: ["Visa"] },
  { symbol: "XOM", name: "Exxon Mobil Corp.", sector: "energy", aliases: ["Exxon Mobil", "Exxon"] },
  { symbol: "MA", name: "Mastercard Inc.", sector: "finance", aliases: ["Mastercard"] },
  { symbol: "ORCL", name: "Oracle Corp.", sector: "tech", aliases: ["Oracle"] },
  { symbol: "COST", name: "Costco Wholesale Corp.", sector: "consumer", aliases: ["Costco"] },
  { symbol: "HD", name: "Home Depot Inc.", sector: "consumer", aliases: ["Home Depot"] },
  { symbol: "PG", name: "Procter & Gamble Co.", sector: "consumer", aliases: ["Procter & Gamble", "P&G"] },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "healthcare", aliases: ["Johnson & Johnson", "J&J"] },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "tech", aliases: ["Netflix"] },
  { symbol: "BAC", name: "Bank of America Corp.", sector: "finance", aliases: ["Bank of America"] },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "healthcare", aliases: ["AbbVie"] },
  { symbol: "CRM", name: "Salesforce Inc.", sector: "tech", aliases: ["Salesforce"] },
  { symbol: "CVX", name: "Chevron Corp.", sector: "energy", aliases: ["Chevron"] },
  { symbol: "WFC", name: "Wells Fargo & Co.", sector: "finance", aliases: ["Wells Fargo"] },
  { symbol: "KO", name: "The Coca-Cola Co.", sector: "consumer", aliases: ["Coca-Cola", "Coke"] },
  { symbol: "TMUS", name: "T-Mobile US Inc.", sector: "telecom", aliases: ["T-Mobile"] },
  { symbol: "CSCO", name: "Cisco Systems Inc.", sector: "tech", aliases: ["Cisco"] },
  { symbol: "PEP", name: "PepsiCo Inc.", sector: "consumer", aliases: ["PepsiCo", "Pepsi"] },
  { symbol: "IBM", name: "International Business Machines Corp.", sector: "tech", aliases: ["IBM"] },
  { symbol: "MS", name: "Morgan Stanley", sector: "finance", aliases: ["Morgan Stanley"] },
  { symbol: "ACN", name: "Accenture plc", sector: "tech", aliases: ["Accenture"] },
  { symbol: "LIN", name: "Linde plc", sector: "materials", aliases: ["Linde"] },
  { symbol: "MCD", name: "McDonald's Corp.", sector: "consumer", aliases: ["McDonald's", "McDonalds"] },
  { symbol: "DIS", name: "The Walt Disney Co.", sector: "media", aliases: ["Disney", "Walt Disney"] },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "healthcare", aliases: ["Abbott"] },
  { symbol: "PM", name: "Philip Morris International Inc.", sector: "consumer", aliases: ["Philip Morris"] },
  { symbol: "GE", name: "General Electric Co.", sector: "industrials", aliases: ["General Electric", "GE"] },
  { symbol: "INTU", name: "Intuit Inc.", sector: "tech", aliases: ["Intuit", "TurboTax"] },
  { symbol: "QCOM", name: "Qualcomm Inc.", sector: "tech", aliases: ["Qualcomm"] },
  { symbol: "DHR", name: "Danaher Corp.", sector: "healthcare", aliases: ["Danaher"] },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "industrials", aliases: ["Caterpillar"] },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", sector: "tech", aliases: ["AMD", "Advanced Micro Devices"] },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc.", sector: "healthcare", aliases: ["Vertex"] },
  { symbol: "TXN", name: "Texas Instruments Inc.", sector: "tech", aliases: ["Texas Instruments"] },
  { symbol: "BKNG", name: "Booking Holdings Inc.", sector: "consumer", aliases: ["Booking Holdings", "Booking.com"] },
  { symbol: "AMAT", name: "Applied Materials Inc.", sector: "tech", aliases: ["Applied Materials"] },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "healthcare", aliases: ["Pfizer"] },
  { symbol: "T", name: "AT&T Inc.", sector: "telecom", aliases: ["AT&T"] },
  { symbol: "NOW", name: "ServiceNow Inc.", sector: "tech", aliases: ["ServiceNow"] },
  { symbol: "LOW", name: "Lowe's Companies Inc.", sector: "consumer", aliases: ["Lowe's", "Lowes"] },
  { symbol: "AMGN", name: "Amgen Inc.", sector: "healthcare", aliases: ["Amgen"] },
  { symbol: "C", name: "Citigroup Inc.", sector: "finance", aliases: ["Citigroup", "Citi"] },
  { symbol: "SPGI", name: "S&P Global Inc.", sector: "finance", aliases: ["S&P Global"] },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", sector: "healthcare", aliases: ["Intuitive Surgical"] },
  { symbol: "UNP", name: "Union Pacific Corp.", sector: "industrials", aliases: ["Union Pacific"] },
  { symbol: "GS", name: "The Goldman Sachs Group Inc.", sector: "finance", aliases: ["Goldman Sachs"] },
  { symbol: "COP", name: "ConocoPhillips", sector: "energy", aliases: ["ConocoPhillips"] },
  { symbol: "HON", name: "Honeywell International Inc.", sector: "industrials", aliases: ["Honeywell"] },
  { symbol: "CMCSA", name: "Comcast Corp.", sector: "media", aliases: ["Comcast"] },
  { symbol: "RTX", name: "RTX Corp.", sector: "industrials", aliases: ["RTX", "Raytheon"] },
  { symbol: "PGR", name: "The Progressive Corp.", sector: "finance", aliases: ["Progressive"] },
  { symbol: "TJX", name: "The TJX Companies Inc.", sector: "consumer", aliases: ["TJX"] },
  { symbol: "EOG", name: "EOG Resources Inc.", sector: "energy", aliases: ["EOG Resources"] },
  { symbol: "SCHW", name: "The Charles Schwab Corp.", sector: "finance", aliases: ["Charles Schwab", "Schwab"] },
  { symbol: "SYK", name: "Stryker Corp.", sector: "healthcare", aliases: ["Stryker"] },
  { symbol: "BA", name: "The Boeing Co.", sector: "industrials", aliases: ["Boeing"] },
  { symbol: "ELV", name: "Elevance Health Inc.", sector: "healthcare", aliases: ["Elevance Health", "Anthem"] },
  { symbol: "DE", name: "Deere & Co.", sector: "industrials", aliases: ["Deere", "John Deere"] },
  { symbol: "ADP", name: "Automatic Data Processing Inc.", sector: "tech", aliases: ["ADP"] },
  { symbol: "VZ", name: "Verizon Communications Inc.", sector: "telecom", aliases: ["Verizon"] },
  { symbol: "NKE", name: "NIKE Inc.", sector: "consumer", aliases: ["Nike"] },
  { symbol: "BSX", name: "Boston Scientific Corp.", sector: "healthcare", aliases: ["Boston Scientific"] },
  { symbol: "MMC", name: "Marsh & McLennan Companies Inc.", sector: "finance", aliases: ["Marsh McLennan"] },
  { symbol: "LRCX", name: "Lam Research Corp.", sector: "tech", aliases: ["Lam Research"] },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "tech", aliases: ["Adobe"] },
  { symbol: "BX", name: "Blackstone Inc.", sector: "finance", aliases: ["Blackstone"] },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", sector: "tech", aliases: ["Palantir"] },
  { symbol: "GILD", name: "Gilead Sciences Inc.", sector: "healthcare", aliases: ["Gilead"] },
  { symbol: "LMT", name: "Lockheed Martin Corp.", sector: "industrials", aliases: ["Lockheed Martin"] },
  { symbol: "MDLZ", name: "Mondelez International Inc.", sector: "consumer", aliases: ["Mondelez"] },
  { symbol: "MU", name: "Micron Technology Inc.", sector: "tech", aliases: ["Micron"] },
  { symbol: "FI", name: "Fiserv Inc.", sector: "tech", aliases: ["Fiserv"] },
  { symbol: "SBUX", name: "Starbucks Corp.", sector: "consumer", aliases: ["Starbucks"] },
  { symbol: "PANW", name: "Palo Alto Networks Inc.", sector: "tech", aliases: ["Palo Alto Networks"] },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc.", sector: "healthcare", aliases: ["Regeneron"] },
  { symbol: "CB", name: "Chubb Limited", sector: "finance", aliases: ["Chubb"] },
  { symbol: "CI", name: "The Cigna Group", sector: "healthcare", aliases: ["Cigna"] },
  { symbol: "UPS", name: "United Parcel Service Inc.", sector: "industrials", aliases: ["UPS", "United Parcel Service"] },
  { symbol: "PH", name: "Parker-Hannifin Corp.", sector: "industrials", aliases: ["Parker Hannifin"] },
  { symbol: "KMI", name: "Kinder Morgan Inc.", sector: "energy", aliases: ["Kinder Morgan"] },
  { symbol: "AMT", name: "American Tower Corp.", sector: "realestate", aliases: ["American Tower"] },
  { symbol: "SHW", name: "The Sherwin-Williams Co.", sector: "materials", aliases: ["Sherwin-Williams"] },
  { symbol: "MO", name: "Altria Group Inc.", sector: "consumer", aliases: ["Altria"] },
  { symbol: "SLB", name: "Schlumberger N.V.", sector: "energy", aliases: ["Schlumberger", "SLB"] },
  { symbol: "CVS", name: "CVS Health Corp.", sector: "healthcare", aliases: ["CVS", "CVS Health"] },
  { symbol: "CDNS", name: "Cadence Design Systems Inc.", sector: "tech", aliases: ["Cadence"] },
  { symbol: "KKR", name: "KKR & Co. Inc.", sector: "finance", aliases: ["KKR"] },
] as const

export const TOP100_SYMBOLS: readonly string[] = TOP100_TICKERS_DATA.map((t) => t.symbol)

export const TOP100_ALIASES: Record<string, readonly string[]> = Object.fromEntries(
  TOP100_TICKERS_DATA.map((t) => [t.symbol, t.aliases])
)
